### ISSUE TITLE
understanding results

### ISSUE THREAD

**Issue by UserName-AnkitSisodia** [jeffgortmaker/pyblp#103]
I am using pyBLP to verify whether my own BLP code in R matches with the results from pyBLP. I have a dataset similar to the automobile dataset. All the columns are exactly same except that I don't have 'air'. Values are from a different country but are all real values.

pyBLP seems to give a different result depending upon the starting values. Very weirdly, in most cases, it outputs the starting values itself as the answer as it doesn't even iterate a second time in the outer loop.

Examples in the attached file
[](url) 
I tried several other starting velues. It eitherr reports the starting values as the answer or gives an error that the inner loop failed to converge (something like no nested fixed point found)

With my R code, I only get one of them as the result. However, my R code is quite basic (only simple BLP instruments, weighting matrix is just an inversion of Z*Z and is never updated, do not handle overflow/underflow etc.). 

This issue happen
[pyBLP_issues.txt](https://github.com/jeffgortmaker/pyblp/files/7917420/pyBLP_issues.txt)
s with or without the suppy 
[pyBLP_issues.txt](https://github.com/jeffgortmaker/pyblp/files/7917421/pyBLP_issues.txt)
side. I might be doing something wrong that is quite basic. In that case, could you let me know as well as put it in the very useful tutorial website.

**Comment by jeffgortmaker** [comment]
It looks like the objective is essentially zero at your starting values. This can happen, for example, if you set up an under-identified problem. What does the `Problem` initialization output looks like, e.g. is the number of demand instruments smaller than the number of parameters?

**Comment by UserName-AnkitSisodia** [comment]
Thanks Jeff,

I think I figured it out. In my product_data csv file, the demand
instruments were not named using the convention 'demand_instruments0' etc.
I suspect that is why the objective was zero at the starting value because
the algorithm did not have any excluded instrument.

After doing that, the algorithm gave results that agreed with my R code,
only much faster. While my R gave the same estimates with different
starting values, pyBLP gave results that were approximately similar
especially if I take the std error into account.

Thank you so much for your response.

theta_starting_values <- c(-43.501,3.612, 4.628, 1.050, 2.056) # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.51 7.9 1.8 5.1
theta_starting_values <- c(-0.1,0.50,7.72,2.3,5.90)            # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.00 7.7 2.3 6.6
theta_starting_values <- c(-4.4,4,5,1,2)                       # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.37 7.9 2.3 6.0
theta_starting_values <- c(-7.6,5.5,5.5,4.4,2.2)               # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.17 7.7 2.4 6.3
theta_starting_values <- c(-1.9,1.9,4.3,8.3,3.1)               # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.26 6.9 2.0 5.2
theta_starting_values <- c(-4.9,2.3,9,3.3,2.2)                 # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.30 7.9 2.3 6.1
theta_starting_values <- c(-2.9,4.6,4.5,7.7,1.2)               # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.25 6.8 2.1 5.4
theta_starting_values <- c(-6.9,8.8,8.5,3.6,6.6)               # R results
yields # -0.01 0.50 7.8 2.3 6.0 # pyBLP yields # -0.01 0.15 7.9 2.4 6.4

Thanks,
Ankit

**Comment by jeffgortmaker** [comment]
Great, glad everything matches reasonably well!

**Comment by UserName-AnkitSisodia** [comment]
Also, after I put initial_update=False in the solve command, pyBLP results
matched exactly with my R code. Just like my R code, pyBLP now reports the
same results regardless of the starting values. Also, the objective value
also matched exactly.

Thanks again for your help.
