### ISSUE TITLE
Wrong "mean own elasticity" in Post-Estimation Bootstrapping Tutorial?

### ISSUE THREAD

**Issue by keatonmill** [jeffgortmaker/pyblp#104]
The `Mean Own Elasticity` entry in [this tutorial](https://pyblp.readthedocs.io/en/stable/_notebooks/tutorial/post_estimation.html#Bootstrapping-Results) is computed using the `aggregates` object. I believe it should be computed using the `means` object, as the table is much more sensible (the means are between the bounds):
![Capture](https://user-images.githubusercontent.com/23563666/152071828-d25da2d8-aa67-4271-84cc-4359b0b2a6ed.PNG)

**Comment by jeffgortmaker** [comment]
Thanks! That's for sure a typo -- I'll leave this open as a reminder to fix it.
