### ISSUE TITLE
Omega matrix Calculation

### ISSUE THREAD

**Issue by mas0088** [jeffgortmaker/pyblp#107]
Thank you for the great repository.

I wonder is there any predefined function to get omega matrix for each market? I see that after the estimation, the result dictionary (nevo_results.to_dict()) includes "omega" key, but the nevo_results.to_dict()["omega"] is empty.

Is there any way to get the omega?

**Comment by chrisconlon** [comment]
I bet it is ownership or Delta (d Q / d P).
