### ISSUE TITLE
Estimating New Prices and Market Shares after Changing Characteristics

### ISSUE THREAD

**Issue by Artashes00** [jeffgortmaker/pyblp#109]
Hi, I am using your repository and it is fantastic.
I estimated a model X1_formulation_with_d = pyblp.Formulation('0 + prices + C(firm_ids)')
                                  X2_formulation = pyblp.Formulation('1 + v1 + v2 + v3')
 
I am new to this repo, so sorry if my question is naive.
Now I want to do a couple of things but I am not able to figure it out. I want to take a market (e.g. market 1) and for that market:
 1.  Draw some vectors from 𝜉𝑗𝑡 distribution. So for each market, I want to draw 20 vectors with the length of J(number of products in that market. How can I access the 𝜉𝑗𝑡?
 2.  I have J products in this market, I want to change the characteristics (v1, v2, v3) of one of the products and for each draws (vector with length J) from 𝜉𝑗𝑡  distribution from the first step to find the optimal set of prices for all J products in the market.
 3. Given these prices, estimate new market shares.            
 
 Any help will be highly appreciated.

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to re-open and/or keep commenting if you have more questions.
