### ISSUE TITLE
extending the feature of aggregate elasticities

### ISSUE THREAD

**Issue by doralindaaaa** [jeffgortmaker/pyblp#113]
Could you consider adding or guiding on how to edit the `compute_aggregate_elasticities` function to achieve the following feature?

I have been trying to extend the original function to calculate the aggregated elasticity by product category. Currently, it only supports the own elasticity by increasing all the products' prices/features. 

Instead, I am interested in seeing how the category A's and B's shares change if all the category A's prices increased. The same for category B's price increase. This would return the 2*2 matrix for each market, rather than a scalar for each market.

Although the idea is simple, I stumbled upon editing the original python codes mainly due to the confusion of multiple classes. So, I really appreciate your input on this.

Thank you!

**Comment by jeffgortmaker** [comment]
I think you should be able to do this with [`ProblemResults.compute_shares`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.ProblemResults.compute_shares.html) by passing it a vector of prices with category A's prices increased. It will return changed shares for all products, including those in categories A and B.

**Comment by doralindaaaa** [comment]
Thank you, it worked as expected!
