### ISSUE TITLE
What is Theta in eq 2

### ISSUE THREAD

**Issue by Artashes00** [jeffgortmaker/pyblp#114]
Maybe this is a silly question but what is \theta in the eq 2 in this tutorial https://pyblp.readthedocs.io/en/stable/_notebooks/tutorial/nevo.html ?
You have mentioned in the notations that it is 𝑃×1 Parameters, but what parameters? Are they the nonlinear parameters? If we speak about the Nevo paper when we do not have demographics, does it mean that \theta is just the \Sigma?

**Comment by jeffgortmaker** [comment]
That's right -- in that equation, theta governs the mixing distribution heterogenous individuals. Without demographics, it's just the parameters in Sigma. In general, "theta" in the package (P x 1) refers to those nonlinear parameters that are optimized over. Typically we can "concentrate out" linear parameters (e.g., alpha, beta), so we don't include them in theta. Does that clear things up?

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to re-open/keep commenting if this didn't clear things up.
