### ISSUE TITLE
Question: Is it possible to restrict the random coefficients to correlate?

### ISSUE THREAD

**Issue by Jakob-Econ** [jeffgortmaker/pyblp#125]
Dear Jeff,

I was wondering if it was possible to restrict random coefficients in the model to correlate in your package?  I was not able to find an option for this in the package: 
![image](https://user-images.githubusercontent.com/76660670/218065465-724116c8-8649-49de-809f-fbcd56658d56.png)

As you can see, gamma is both in front of z but also delta z, where it is multiplied with tau, however. 

Many thanks!

**Comment by Jakob-Econ** [comment]
The parameters are assumed to be distributed normally - I will try to see whether I could implement this with rc_types or agent_data. Thank you!

**Comment by jeffgortmaker** [comment]
The product of normals isn't very tractable, so my guess is you won't be able to exactly implement the distribution. But an approximation is always possible.

I'll close this issue for now, but please re-open/keep commenting if you have other questions.
