### ISSUE TITLE
Nesting parameter not optimised, stuck at initial value

### ISSUE THREAD

**Issue by Fijiman001** [jeffgortmaker/pyblp#131]
Dear Community,

I am relatively new to coding in python and using the pyblp package. I am using to do merger simulation with a nested logit demand model. I am analysing the US airline industry for my bachelor's thesis and I have encountered two main problems:
1. Nesting parameter is not estimated, stays at initial value
2. I cannot simultaneously estimate the supply side (marginal cost), presumably because I don't have agent_formulation defined. I do not see how I can implement this with my data set. Instead I estimate the supply side seperately using OLS.

'      matplotlib inline

import pyblp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pyblp.options.digits = 2
pyblp.options.verbose = False
pyblp.__version__

product_data = pd.read_csv('/content/df.csv')
product_data.head()

product_data=product_data.rename(columns={"Price": "prices", "OwnShare": "shares", "MkID": "market_ids", "FirmID": "firm_ids"})

def solve_nl(df):
    groups = df.groupby(['market_ids', 'nesting_ids'])
    nl_formulation = pyblp.Formulation('1 + prices + Stops + Distance + Distance2 + DL + UA + US + CO + NW + WN + LCC + Other + OriginConn')
    problem = pyblp.Problem(nl_formulation, df)
    return problem.solve(rho=0.3)

df1 = product_data.copy()
df1['nesting_ids'] = 1
nl_results1 = solve_nl(df1)
nl_results1

![image](https://user-images.githubusercontent.com/126694299/225433151-9e1efd62-640f-416d-8023-6c563c70ad4e.png)
Marginal cost:
import statsmodels.api as sm

% Define dependent and independent variables
X = product_data[['Stops', 'Distance', 'Hub', 'DL', 'UA', 'US', 'CO', 'NW', 'WN', 'LCC', 'Other']]
Y = costs

%Add constant term to independent variables
X = sm.add_constant(X)

%Fit OLS model
model = sm.OLS(Y, X).fit()

%Print summary of results
print(model.summary())

The specification I want is:
marginal costs ~  Constant + Stops + Distance + ConnMC + 
                                DL + UA + US + CO + NW + WN+ LCC + Other
'
I have previously to no avail, tried to include the supply side formulation in the product formulation

[df_new.csv](https://github.com/jeffgortmaker/pyblp/files/10984147/df_new.csv)

**Comment by jeffgortmaker** [comment]
Did you specify an instrument for the nesting parameter? You're probably underidentified, i.e. more parameters than instruments. See #122. (fyi you can more easily format code and output with backticks: ` )

**Comment by Fijiman001** [comment]
> Did you specify an instrument for the nesting parameter? You're probably underidentified, i.e. more parameters than instruments. See #122. (fyi you can more easily format code and output with backticks: ` )

I'm guessing you mean the "demand_instruments0" and so on. No these are not specified in the data set, I believed one could do without them

**Comment by jeffgortmaker** [comment]
Nope, you absolutely need instruments. BLP-style demand estimation unfortunately requires a good amount of background knowledge to do correctly. I recommend starting with Nevo's (2002) [practitioner's guide](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1430-9134.2000.00513.x?casa_token=vc0Pu2CPg-oAAAAA:_VtRNu6pkfDekxPGZwlwdtJ89Ou3yrouNYYuy_e0pU7TquaKeKSZbVOTyEdG8sHGQcVALxQN5Eci), and reading other papers with similar specifications as you, e.g. what instruments they use for the nesting parameter. A classic choice is the number of other products in the same nest.
