### ISSUE TITLE
The estimated parameters are very large, even if I set the bounds

### ISSUE THREAD

**Issue by ambition-hjm** [jeffgortmaker/pyblp#133]
Hi， I encountered a problem when used the pyblp. The picture below shows my code and results. No matter how I adjusted the parameters, the parameters of the final result were very large. Is there anyway to solve it ? because all of the parameters are large. not just one or two ! please help me

![1682167674440](https://user-images.githubusercontent.com/55944440/233785597-cd305ef6-5a49-42fb-820b-7e083ec3b0de.png)

**Comment by jeffgortmaker** [comment]
It's hard to tell what could be going on without more info. There's a lot of stuff going on here, and your single objective evaluation took around 13 minutes.

Can you simplify things (e.g. restrict to a single market, reduce the number of parameters, etc) to put together a [minimum working example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (MWE) that exhibits the same problem and has the full problem configuration in one place?

**Comment by jeffgortmaker** [comment]
I'm going to close this for now. But please re-open it / keep commenting if you're still having trouble.
