### ISSUE TITLE
Trouble running the nevo tutorial

### ISSUE THREAD

**Issue by hibasameen** [jeffgortmaker/pyblp#136]
Hi there,

I've installed pyblp and all the relevant dependencies as set out here: https://pypi.org/project/pyblp/#description.

I'm running the Nevo random coefficients tutorial and the pyblp.Problem class does not initialise. I get the following traceback:

---------------------------------------------------------------------------
DeprecationWarning                        Traceback (most recent call last)
<ipython-input-23-4e17fe47d711> in <module>
----> 1 mc_problem = pyblp.Problem(product_formulations, product_data, integration=mc_integration)
      2 mc_problem

~/opt/anaconda3/lib/python3.7/site-packages/pyblp/economies/problem.py in __init__(self, product_formulations, product_data, agent_formulation, agent_data, integration, rc_types, epsilon_scale, costs_type, add_exogenous)
   1548 
   1549         # detect any problems with the product data
-> 1550         self._detect_collinearity(add_exogenous)
   1551 
   1552         # output information about the initialized problem

~/opt/anaconda3/lib/python3.7/site-packages/pyblp/economies/economy.py in _detect_collinearity(self, added_exogenous)
    186         # check each matrix for collinearity
    187         for name, labels in matrix_labels.items():
--> 188             collinear, successful = precisely_identify_collinearity(self.products[name])
    189             common_message = "To disable collinearity checks, set options.collinear_atol = options.collinear_rtol = 0."
    190             if (self.ED > 0 and name in {'X1', 'ZD'}) or (self.ES > 0 and name in {'X3', 'ZS'}):

~/opt/anaconda3/lib/python3.7/site-packages/pyblp/utilities/algebra.py in precisely_identify_collinearity(x)
     47             with warnings.catch_warnings():
     48                 warnings.filterwarnings('error')
---> 49                 r = scipy.linalg.qr(x, mode='r')[0]
     50                 collinear = np.abs(r.diagonal()) < options.collinear_atol + options.collinear_rtol * x.std(axis=0)
     51         except (ValueError, scipy.linalg.LinAlgError, scipy.linalg.LinAlgWarning):

~/.local/lib/python3.7/site-packages/scipy/linalg/decomp_qr.py in qr(a, overwrite_a, lwork, mode, pivoting, check_finite)
    139         geqrf, = get_lapack_funcs(('geqrf',), (a1,))
    140         qr, tau = safecall(geqrf, "geqrf", a1, lwork=lwork,
--> 141                            overwrite_a=overwrite_a)
    142 
    143     if mode not in ['economic', 'raw'] or M < N:

~/.local/lib/python3.7/site-packages/scipy/linalg/decomp_qr.py in safecall(f, name, *args, **kwargs)
     18         kwargs['lwork'] = -1
     19         ret = f(*args, **kwargs)
---> 20         kwargs['lwork'] = ret[-2][0].real.astype(numpy.int)
     21     ret = f(*args, **kwargs)
     22     if ret[-1] < 0:

~/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py in __getattr__(attr)
    295     if sys.platform == "linux" and use_hugepage is None:
    296         # If there is an issue with parsing the kernel version,
--> 297         # set use_hugepages to 0. Usage of LooseVersion will handle
    298         # the kernel version parsing better, but avoided since it
    299         # will increase the import time. See: #16679 for related discussion.

DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I tried installing an older verison of NumPy but still get the same result. Any idea about what might be going wrong?

Thanks for your help!

**Comment by jeffgortmaker** [comment]
Great!
