### ISSUE TITLE
Question: When using pyblp.parallel() to run problem.solve(), How can I make sure that each partition has enough RAM?

### ISSUE THREAD

**Issue by Jakob-Econ** [jeffgortmaker/pyblp#145]
Hi Jeff,

 I keep running into the problem, that when using parallel() and solve(), I get the error message that there is not enough space for some matrix of size 4-5 GB (Dataset size: 1.3million). Do you have an idea how to fix that? I tried using less partitions than I have cores, e.g. with 112 cores, pyblp.parallel(28).

Thanks a ton,
Jakob

**Comment by jeffgortmaker** [comment]
If you're using a cluster, core-specific memory constraints will be determined by the job scheduling system, which I can't help with -- you should ask your cluster tech support.

In general, pooling memory across cores, parallelization will use more memory than a non-parallelized approach. This is because each market's data needs to be copied, serialized, and sent to a separate process to be handled there.

What I can possibly help with is brainstorming how to reduce your overall memory usage. But I'll need some more information about what you're doing to be helpful, e.g.

1. Do you also run into memory issues without parallelization?
2. Are you using any micro data?
3. Analytic gradients?
4. Any guesses what could be taking up space?
5. Etc.

**Comment by Jakob-Econ** [comment]
I was using a non-shared memory environment (mpi), with each node having 28 cores and 256GB of memory (in total 112 cores). I requested for example pyblp.parallel(56), but I am not sure how pyblp and python divide up the memory. As each core has its memory, here e.g. around 9GB. In that case, each "worker" should have had 2 cores and therefore 18GB of memory.

I am now trying to use a shared memory environment (openmp) with 504 GB. Is it possible to use pyblp parallel so that the workers share the memory? In julia e.g. it would be possible through multi-threading.

1. No
2. No
3. Yes, the optimization BFGS that you provide uses gradients afaik
4. Not sure, I think that it has to do with pyblp.solve creating a lot of temporary objects that, given the dataset size of around 4/5 GB, is too much to handle for 18GB.

**Comment by Jakob-Econ** [comment]
Ok thanks a lot, I understand better now.

I am trying this, but I don't know what I am missing. This peace of code takes forever to run, why would that be the case? Maybe I need to reinstall the package.

```
lin_form = pyblp.Formulation('1 + prices + size +premium + vanilla + chocolate', absorb = 'C(quarter)')

rand_form = pyblp.Formulation("0 + prices")

blp_form = (lin_form, rand_form)

# specify the integration method
int_method = pyblp.Integration('monte_carlo', size=50)

problem = pyblp.Problem(
product_formulations = blp_form, 
product_data = dt,
integration = int_method)

results = problem.solve(
sigma = np.diag(np.ones(1)),
method = '1s',
optimization=pyblp.Optimization('return'))
```

Thanks!!

**Comment by jeffgortmaker** [comment]
No idea without more information. In general it's rare for a problem to be set up correctly (without any data errors, configuration problems, etc.) the first time, so you'll almost always have to debug by looking at logs, inspecting data, etc.

For example, you can configure your `iteration` routine to use the `universal_display`, which will output information iteration-by-iteration in the contraction. Probably, it's just not converging in a market or two, which is indicative either of a too-tight default termination tolerance, or some data problem in the market where it's not converging, both, or something related.

(PS: remember to set your seed when using Monte Carlo integration.)

**Comment by Jakob-Econ** [comment]
Ok, I see, so this 
```
method = '1s',
optimization=pyblp.Optimization('return'))
```
calculates the contraction once? 
I thought it would not do that, but yes, then of course, you cannot solve this!

**Comment by jeffgortmaker** [comment]
Yep, that's right. And if you want to just return at the starting delta values (just to see whether things are working), you can do `iteration=pyblp.Iteration('return')`. Of course the results won't make much sense.

Another thing to make things faster is `check_optimality='gradient'` -- skips computing the Hessian.

**Comment by Jakob-Econ** [comment]
Ok thanks, I will see what's up in the data and get back to you here about the memory usage once I have figured it out.

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but please do keep commenting / re-open if you end up figuring this out.
