### ISSUE TITLE
ProblemResults question

### ISSUE THREAD

**Issue by shmaykol** [jeffgortmaker/pyblp#153]
Hi,

I would like to use the ProblemResults.compute_elasticities functionality, but I would like to do so with different (exogenously provided) prices to the ones found in the data. How do I do so?

**Comment by jeffgortmaker** [comment]
You're probably going to want to create a `Simulation` with your problem configuration and estimates, but tweak the prices. You can compute elasticities with `SimulationResults.compute_elasticities`. You'll want to double-check that when you provide the same prices in the data, this method returns the same thing as `ProblemResults.compute_elasticities`.

**Comment by shmaykol** [comment]
Great. Thanks. To clarify: I would want to use replace_endogenous with method='return'?

How would I create a Simulation where I also tweaked exogenous characteristics, but kept estimated parameters the same? I want to pass it the estimated Problem parameters, but would otherwise want to change a single characteristic. I assume I could pass a modified product_data? If I want to try N different versions of product characteristics and prices, should I create a different Simulation each time, or is there a more efficient way to do so with one Simulation class?

**Comment by jeffgortmaker** [comment]
Yes, that's right. With `method='return'`, you should set `prices` equal to your new exogenous prices. Along with elasticities, market shares will also change accordingly.

When you initialize the `Simulation`, you'd pass your estimated parameters and `ProblemResults.xi` (plus `ProblemResults.xi_fe` if you have absorbed FEs), and you could just tweak your prices when calling `replace_endogenous`. If you want to tweak other characteristics you'd do so when specifying `product_data`.

And yes, if you want to try N different prices, you can use N different `prices` when calling `replace_endogenous`. If you also want to tweak other characteristics, you'd have to create N different `Simulation`s.

**Comment by shmaykol** [comment]
Great. Finally - what if I want to compute not elasticities but (i) utility derivatives for each individual directly (w.r.t. prices and X_1, the altered exogenous characteristic) and (ii) shares? I assume the second would be Simulation.compute_shares, but what about the first?

**Comment by jeffgortmaker** [comment]
That's right for (ii). And `replace_endogenous` will also compute them.

For (i), PyBLP certainly computes these under the hood, but they're sufficiently simple that there isn't a user-facing function for computing them. I recommend just computing these yourself directly. You can access the underlying product and agent data with `Simulation.products` and `Simulation.agents`. Computing them market-by-market is probably going to be easiest (so selecting just one market at a time from these record arrays).

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to keep commenting / re-open it.
