### ISSUE TITLE
Coding base level in categorical variables in pyblp

### ISSUE THREAD

**Issue by claudiolucinda** [jeffgortmaker/pyblp#154]
Hi Jeff,

I have a model with a large(-ish) number of fixed effects in X1. Originally I absorbed them, which was OK, and then I realized I had to have the coefficients for these fixed effects. However, when I put them back in the "non-absorbed" part of X1 the optimizer seems to have some numerical difficulties. I tried using the patsy options for setting the default category on the "C" operator, but they do not seem to work and I read in pyblp docs that arguments are not supported. Is that correct? If so, is there another way to add these fixed effects or will I need to create them manually and add them to the model?

Thanks a lot for your time,
Claudio Lucinda

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to keep commenting if you have other questions!
