### ISSUE TITLE
Nested Logit Post Estimation Results 

### ISSUE THREAD

**Issue by klinnertj** [jeffgortmaker/pyblp#164]
Hi, 
I fairly new to estimating nested logit models but I am estimating a nested logit for a project. 
I have estimated the model successfully (my code converges and my estimates make sense). My issue lies in additional results. Since I am new to estimating this type of model I am unsure what results I can or should present.  I wanted to start of with estimating the elasticities showing the within and across elasticities. When I do that (using elasticities = nl_results2.compute_elasticities(); single_market = product_data['market_ids'] == '2961'; plt.colorbar(plt.matshow(elasticities[single_market]));)  I get the error "ZeroDivisionError: float division by zero". After looking at the elasticities I figured it was because I also get NaN values. I don't know if it is something I am doing wrong or because i should only estimate the elasticities within a nest. Any help regarding this or any other suggestions on which results to presents are greatly appreciated. 

Thank you, 

Jorge

**Comment by jeffgortmaker** [comment]
You should take a look at the `Returns` field in the [docs](https://pyblp.readthedocs.io/en/latest/_api/pyblp.ProblemResults.compute_elasticities.html)!

> Estimated $J_t \times J_t$ matrices of elasticities of demand, $\varepsilon$. If `market_id` was not specified, matrices are estimated in each market $t$ and stacked. Columns for a market are in the same order as products for the market. If a market has fewer products than others, extra columns will contain `numpy.nan`.

You can either just select the first $J_t$ columns you care about or use the `market_id` field in `compute_elasticities`.

In general, the results you present depend on what you're trying to do with the model. Often, this is some type of prediction exercise or simulation. The goal is often not the estimates themselves, but if it is, one place to look for how to describe your model estimates is my series of lecture notes/examples on BLP [here](https://github.com/Mixtape-Sessions/Demand-Estimation). I don't go too much into nested logit, but some of the advice should be applicable.

**Comment by klinnertj** [comment]
Great!
Just so other people know the following solved my issue (which was under the link Jeff provided):
  elasticities = nl_results2.compute_elasticities(name='prices', market_id=market_ids)
  plt.colorbar(plt.matshow(elasticities));

I will also check out your slides. Thank you!
