### ISSUE TITLE
PyBLP markets without prices

### ISSUE THREAD

**Issue by luisignaciomenendez** [jeffgortmaker/pyblp#165]
Hello,

I'm trying to estimate BLP but my market set up is different from the one that PyBLP incorporates. I have a market without prices (pure horizontal differentiation) and just product characteristics. Characteristics are endogenous  and therefore need to be instrumented. I wondered if this set up can be accommodated into the current PyBLP set up somehow.

Thanks in advance

**Comment by jeffgortmaker** [comment]
For sure: https://github.com/jeffgortmaker/pyblp/issues/130 is one solution. Another hack is to have some arbitrary values for `prices` (not constant so you don't get a warning) but fix their element in `beta` (an argument to `Problem.solve`) to zero.

At this point I wish I'd designed the API to handle setups without prices more elegantly, but mistakes were made.

**Comment by luisignaciomenendez** [comment]
Thanks a lot for the quick reply, Jeff!

I tried indeed forcing the coefficient to 0 as follows:

`X1_formulation = pyblp.Formulation('0 + prices + char0 + char1 ')
X2_formulation = pyblp.Formulation('0+ char0 + char1')
product_formulations = (X1_formulation, X2_formulation)
results1 = mc_problem.solve(sigma=np.eye(2),beta=np.array([0, np.nan, np.nan]), optimization=bfgs)
`

I still cannot recover the true parameters (I'm simulating data). In theory, an specification where there are 2 product characteristics that enter non-linearly and 2 instruments `demand_instruments0	demand_instruments1`  (one for each characteristic) should be correct, right?

Thanks in advance
