### ISSUE TITLE
Issue on Formulation package, the new bug edit didn't help

### ISSUE THREAD

**Issue by NedaMZN** [jeffgortmaker/pyblp#19]
alueError                                Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in parse_expression(string, mark_categorical)
    588         try:
--> 589             expression = sympy.parsing.sympy_parser.parse_expr(string, mapping, [transform_tokens], evaluate=False)
    590             str(expression)

~\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py in parse_expr(s, local_dict, transformations, global_dict, evaluate)
    959 
--> 960     code = stringify_expr(s, local_dict, global_dict, transformations)
    961 

~\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py in stringify_expr(s, local_dict, global_dict, transformations)
    865     for transform in transformations:
--> 866         tokens = transform(tokens, local_dict, global_dict)
    867 

~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in transform_tokens(tokens, *_)
    559             if code not in {token.NAME, token.OP, token.NUMBER, token.ENDMARKER}:
--> 560                 raise ValueError(f"The token '{value}' is invalid.")
    561             if code == token.OP and value not in {'+', '-', '*', '/', '**', '(', ')'}:

ValueError: The token '' is invalid.

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in parse_term_expression(term)
    531         try:
--> 532             expression *= parse_expression(factor.name())
    533         except Exception as exception:

~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in parse_expression(string, mark_categorical)
    592         except (TypeError, ValueError) as exception:
--> 593             raise ValueError(f"The expression '{string}' is malformed.") from exception
    594 

ValueError: The expression 'prices' is malformed.

The above exception was the direct cause of the following exception:

PatsyError                                Traceback (most recent call last)
<ipython-input-17-c32fb5bf489a> in <module>
      2 #linear_formula = pyblp.Formulation('0 + prices', absorb='C(product_ids)')
      3 # These are X_2 formulas
----> 4 nonlinear_formula = pyblp.Formulation('1 + prices + sugar + mushy')
      5 
      6 product_formulations = (linear_formula,nonlinear_formula)

~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in __init__(self, formula, absorb, absorb_method)
    136 
    137         # parse the terms into SymPy expressions and extract variable names
--> 138         self._expressions = [parse_term_expression(t) for t in self._terms]
    139         self._absorbed_expressions = [parse_term_expression(t) for t in self._absorbed_terms]
    140         self._names = {str(s) for e in self._expressions for s in e.free_symbols}

~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in <listcomp>(.0)
    136 
    137         # parse the terms into SymPy expressions and extract variable names
--> 138         self._expressions = [parse_term_expression(t) for t in self._terms]
    139         self._absorbed_expressions = [parse_term_expression(t) for t in self._absorbed_terms]
    140         self._names = {str(s) for e in self._expressions for s in e.free_symbols}

~\Anaconda3\lib\site-packages\pyblp\configurations\formulation.py in parse_term_expression(term)
    532             expression *= parse_expression(factor.name())
    533         except Exception as exception:
--> 534             raise patsy.PatsyError("Failed to parse a term.", factor.origin) from exception
    535     return expression
    536 

PatsyError: Failed to parse a term.
    1 + prices + sugar + mushy
        ^^^^^^

**Comment by jeffgortmaker** [comment]
Thanks for the report. I'm not sure what's going on here, yet. I haven't had trouble parsing that formula.

Can you (1) post the output of ``conda list`` so I can see what package versions you have installed, and (2) post the relevant section of your code? [Using backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) makes output and code more readable.

**Comment by alborotogarcia** [comment]
@jeffgortmaker Can you try installing pyblp from a fresh Anaconda3/Miniconda3 environment or just from pip3. It seems the error comes from Formulation class even if it uses patsy 0.5.1
Breaking at
 --> 531             raise patsy.PatsyError("Failed to parse a term.", factor.origin) from exception

**Comment by alborotogarcia** [comment]
Edit: in my case my pip list returns the following:
Package                   Version            
------------------------- -------------------
absl-py                   0.8.1              
aiohttp                   3.6.2              
alembic                   1.3.2              
aniso8601                 8.0.0              
apache-airflow            1.10.7             
apispec                   1.3.3              
argcomplete               1.11.0             
argh                      0.26.2             
arviz                     0.6.0              
asn1crypto                0.24.0             
astor                     0.8.0              
async-timeout             3.0.1              
attrs                     19.3.0             
awscli                    1.16.309           
Babel                     2.7.0              
backcall                  0.1.0              
bcrypt                    3.1.7              
bleach                    3.1.0              
blinker                   1.4                
bokeh                     1.4.0              
boto3                     1.10.45            
botocore                  1.13.45            
cached-property           1.5.1              
cachetools                3.1.1              
cattrs                    0.9.0              
certifi                   2019.9.11          
cffi                      1.13.2             
cftime                    1.0.4.2            
chardet                   3.0.4              
Click                     7.0                
cloudpickle               1.2.2              
colorama                  0.4.1              
colorcet                  2.0.2              
colorlog                  4.0.2              
configparser              3.5.3              
croniter                  0.3.30             
cryptography              2.8                
cycler                    0.10.0             
decorator                 4.4.1              
defusedxml                0.6.0              
dill                      0.3.1.1            
docker                    4.1.0              
docutils                  0.15.2             
doit                      0.32.0             
econml                    0.6                
entrypoints               0.3                
enum34                    1.1.6              
fabric                    2.5.0              
ffmpeg                    1.4                
findspark                 1.3.0              
Flask                     1.1.1              
Flask-Admin               1.5.4              
Flask-AppBuilder          2.2.1              
Flask-Babel               0.12.2             
Flask-Bcrypt              0.7.1              
Flask-Caching             1.3.3              
Flask-JWT-Extended        3.24.1             
Flask-Login               0.4.1              
Flask-OpenID              1.2.5              
Flask-RESTful             0.3.7              
Flask-SQLAlchemy          2.4.1              
flask-swagger             0.2.13             
Flask-Testing             0.7.1              
Flask-WTF                 0.14.2             
funcsigs                  1.0.2              
future                    0.16.0             
gast                      0.2.2              
ghp-import2               1.0.1              
google-auth               1.7.0              
google-auth-oauthlib      0.4.1              
google-pasta              0.1.8              
graphviz                  0.13.2             
grpcio                    1.25.0             
gunicorn                  19.10.0            
gym                       0.15.4             
h5py                      2.10.0             
holoviews                 1.12.7             
husl                      4.0.3              
hvplot                    0.5.2              
idna                      2.6                
idna-ssl                  1.1.0              
imageio                   2.6.1              
imbalanced-learn          0.6.1              
importlib-metadata        0.23               
inflection                0.3.1              
invoke                    1.3.0              
ipykernel                 5.1.3              
ipyparallel               6.2.4              
ipython                   7.9.0              
ipython-genutils          0.2.0              
ipywidgets                7.5.1              
iso8601                   0.1.12             
itsdangerous              1.1.0              
jedi                      0.15.1             
Jinja2                    2.10.3             
jmespath                  0.9.4              
joblib                    0.14.1             
json-merge-patch          0.2                
json5                     0.8.5              
jsonschema                3.1.1              
jupyter                   1.0.0              
jupyter-client            5.3.4              
jupyter-console           6.0.0              
jupyter-core              4.6.1              
jupyter-http-over-ws      0.0.6              
jupyterlab                1.2.4              
jupyterlab-server         1.0.6              
Keras-Applications        1.0.8              
Keras-Preprocessing       1.1.0              
keyring                   10.6.0             
keyrings.alt              3.0                
kiwisolver                1.1.0              
lazy-object-proxy         1.4.3              
llvmlite                  0.30.0             
lockfile                  0.12.2             
Logbook                   1.5.3              
lxml                      4.4.2              
Mako                      1.1.0              
Markdown                  2.6.11             
MarkupSafe                1.1.1              
marshmallow               2.19.5             
marshmallow-enum          1.5.1              
marshmallow-sqlalchemy    0.21.0             
matplotlib                3.1.1              
metakernel                0.24.3             
micawber                  0.5.1              
mistune                   0.8.4              
more-itertools            5.0.0              
mpmath                    1.1.0              
multidict                 4.7.2              
mysql-connector-python-rf 2.2.2              
mysqlclient               1.4.6              
natsort                   6.2.0              
nbconvert                 5.6.1              
nbformat                  4.4.0              
ndg-httpsclient           0.5.1              
netCDF4                   1.5.3              
Nikola                    8.0.3              
nose                      1.3.7              
notebook                  6.0.2              
numba                     0.46.0             
numpy                     1.17.3             
oauthlib                  3.1.0              
opencv-python             4.1.2.30           
opt-einsum                3.1.0              
packaging                 19.2               
pandas                    0.25.3             
pandas-datareader         0.8.1              
pandas-ml                 0.6.1              
pandocfilters             1.4.2              
param                     1.9.2              
paramiko                  2.7.1              
parso                     0.5.1              
passlib                   1.7.2              
pathtools                 0.1.2              
patsy                     0.5.1              
pendulum                  1.4.4              
pexpect                   4.7.0              
phpserialize              1.3                
pickleshare               0.7.5              
piexif                    1.1.3              
Pillow                    6.2.1              
pip                       19.3.1             
pipenv                    2018.11.26         
pluggy                    0.13.1             
portalocker               1.5.2              
prison                    0.1.2              
prometheus-client         0.7.1              
prompt-toolkit            2.0.10             
protobuf                  3.10.0             
psutil                    5.6.7              
psycopg2                  2.8.4              
ptyprocess                0.6.0              
py                        1.8.0              
py4j                      0.10.7             
pyarrow                   0.15.1             
pyasn1                    0.4.7              
pyasn1-modules            0.2.7              
pybase62                  0.4.3              
pyblp                     0.8.1              
pycparser                 2.19               
pycrypto                  2.6.1              
pyct                      0.4.6              
pygal                     2.4.0              
pyglet                    1.3.2              
Pygments                  2.4.2              
pygobject                 3.26.1             
pyinotify                 0.9.6              
PyJWT                     1.7.1              
pymc3                     3.8                
PyMySQL                   0.9.3              
PyNaCl                    1.3.0              
pyOpenSSL                 19.1.0             
pyparsing                 2.4.4              
Pyphen                    0.9.5              
pyrsistent                0.15.5             
PyRSS2Gen                 1.1                
pyspark                   2.4.4              
pytest                    5.3.2              
python-apt                1.6.4              
python-daemon             2.1.2              
python-dateutil           2.8.1              
python-editor             1.0.4              
python3-openid            3.1.0              
pytz                      2019.3             
pytzdata                  2019.3             
pyviz-comms               0.7.2              
pyxdg                     0.25               
PyYAML                    5.2                
pyzmq                     18.1.0             
qtconsole                 4.5.5              
Quandl                    3.4.8              
requests                  2.22.0             
requests-oauthlib         1.3.0              
rsa                       3.4.2              
ruamel.yaml               0.16.5             
ruamel.yaml.clib          0.2.0              
s3transfer                0.2.1              
scikit-learn              0.22               
scikit-surprise           1.1.0              
scipy                     1.4.1              
scour                     0.36               
seaborn                   0.9.0              
SecretStorage             2.3.1              
Send2Trash                1.5.0              
setproctitle              1.1.10             
setuptools                42.0.2             
six                       1.13.0             
smartypants               2.0.1              
sparse                    0.8.0              
spylon                    0.3.0              
spylon-kernel             0.4.1              
SQLAlchemy                1.3.12             
SQLAlchemy-JSONField      0.9.0              
SQLAlchemy-Utils          0.36.1             
statsmodels               0.10.2             
sympy                     1.5                
tabulate                  0.8.6              
tb-nightly                2.1.0a20191106     
tenacity                  4.12.0             
termcolor                 1.1.0              
terminado                 0.8.2              
testpath                  0.4.4              
text-unidecode            1.2                
tf-estimator-nightly      2.0.0.dev2019110709
tf-nightly-gpu            2.1.0.dev20191106  
tfp-nightly               0.9.0.dev20191224  
Theano                    1.0.4              
thrift                    0.13.0             
toml                      0.10.0             
torch                     1.3.1              
torchvision               0.4.2              
tornado                   6.0.3              
tqdm                      4.41.0             
traitlets                 4.3.3              
typing                    3.7.4.1            
typing-extensions         3.7.4.1            
typogrify                 2.0.7              
tzlocal                   1.5.1              
unicodecsv                0.14.1             
Unidecode                 1.1.1              
urllib3                   1.25.6             
uuid0                     0.2.7              
virtualenv                15.1.0             
virtualenv-clone          0.5.3              
watchdog                  0.9.0              
wcwidth                   0.1.7              
webencodings              0.5.1              
websocket-client          0.56.0             
Werkzeug                  0.16.0             
wheel                     0.33.6             
widgetsnbextension        3.5.1              
wrapt                     1.11.2             
WTForms                   2.2.1              
xarray                    0.14.1             
xgboost                   1.0.0-SNAPSHOT     
xlrd                      1.2.0              
Yapsy                     1.12.2             
yarl                      1.4.2              
zipp                      0.6.0              
zope.deprecation          4.4.0

**Comment by jeffgortmaker** [comment]
Thanks for the report. If the problem is the same as the one I fixed in [this commit](https://github.com/jeffgortmaker/pyblp/commit/5441df6335115de011ae0d606991bb3280e8f28f), it's a problem with the new version 1.5 of SymPy. I haven't included the fix yet in a stable version of PyBLP.

Can you try either downgrading SymPy or using the dev version of this package by cloning this repo?

**Comment by alborotogarcia** [comment]
Thanks @jeffgortmaker finally got Formulations working installing sympy and pyblp from git, although unfortunately I can't get Integrations working, e.g. running the following statement from the nevo notebook:

mc_integration = pyblp.Integration('monte_carlo', size=50, seed=0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-942a349bd2e3> in <module>
----> 1 mc_integration = pyblp.Integration('monte_carlo', size=50, seed=0)
      2 mc_integration

TypeError: __init__() got an unexpected keyword argument 'seed'

**Comment by jeffgortmaker** [comment]
I recently changed the API for `Integration` so that you now specify the seed as a field in `specification_options`, so something like `specification_options={'seed': 0}`. This new way of specifying things makes more sense now that there are more integration routines -- sorry about that.

I recommend using the [dev documentation](https://pyblp.readthedocs.io/en/latest/_api/pyblp.Integration.html) if you're using the cloned repo. Although I still have to update that notebook before releasing the next version.

**Comment by alborotogarcia** [comment]
@jeffgortmaker I'll do it thank you so much!
