### ISSUE TITLE
Add benchmarking features to results object

### ISSUE THREAD

**Issue by chrisconlon** [jeffgortmaker/pyblp#2]
Include standard BLP benchmarking comparisons to results object.
1. Run time
2. Number of Function/Gradient Evals/Major Iterations.
3. Total number of contraction evaluations.

**Comment by jeffgortmaker** [comment]
Reopening to do more here.

 - Major iterations can be extracted from SciPy optimization methods, and doing so should also be possible with Knitro. This is a good opportunity to standardize the return signature of custom optimization and iteration methods: ``(final, iterations, converged)``.
 - ``Results.contraction_evaluations`` and its iteration counterpart should be matrices in which rows are in the same order as ``Results.unique_market_ids``.
 - There should be a ``Results.last_results`` attribute for GMM steps after the first.
 - There should be ``Results.cumulative_`` counterparts to each count or time attribute for convenience.
 - The time it takes to compute results for a step should also be recorded. This could be done by passing only the optimization start and end times to ``Results`` and letting it do the math after it computes standard errors and updated weighting matrices.
