### ISSUE TITLE
Formulas with large number of columns in X

### ISSUE THREAD

**Issue by shoshievass** [jeffgortmaker/pyblp#23]
Is there any support for using a dynamic variable trick for X1 and X2?

E.g. `X1 = [x1_1,x1_2,x1_3,...x1_100]` and I put in a formula of `0 + prices + x1_%` or something like that instead of writing out the full formula? Or putting in `X1` as a whole?

I apologize for the novice issues!

**Comment by jeffgortmaker** [comment]
Nope, unfortunately I don't think that's possible with `patsy`-type formulas. And I've tried to not complicate their syntax too much.

The best way of doing this is probably to dynamically construct your formula string:

```
formula = ' + '.join(f'x1_{i + 1}' for i in range(100))
```
