### ISSUE TITLE
Accessing Monte Carlo NS Draws

### ISSUE THREAD

**Issue by shoshievass** [jeffgortmaker/pyblp#24]
Unless I've misunderstood, there's currently no way to access the monte carlo draws from the integration step in the `results` class. Is that right? Would it be possible to change that?

**Comment by jeffgortmaker** [comment]
You should be able to access them via [`results.problem.agents`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Agents.html#pyblp.Agents). I've generally tried to make standard objects like that available, which unfortunately comes with the cost of having tons of class attributes that are hard to sort through.

**Comment by shoshievass** [comment]
Ah clever! Thanks for the help :)
