### ISSUE TITLE
log prices gives divide by zero issues in simulation

### ISSUE THREAD

**Issue by amandeep0** [jeffgortmaker/pyblp#38]
I was trying to run the simulation using a formulation which has log(prices). I am getting these errors "<string>:2: RuntimeWarning: divide by zero encountered in log" which initializing the simulation.

**Comment by jeffgortmaker** [comment]
I'm guessing the prices solved for by the simulation have a few zeros. In practice, log terms like this create trouble for numerical estimation routines because a few "extreme" values can create errors. Without more info I can't say much more.

**Comment by amandeep0** [comment]
Actually. I did not even solve for prices. I just initialized the simulation class, using the example in docs, but with log prices instead. 

id_data = pyblp.build_id_data(T=50, J=20, F=10)
integration = pyblp.Integration('product', 9)
simulation = pyblp.Simulation(
   product_formulations=(
       pyblp.Formulation('1 + log(prices) + x'),
       pyblp.Formulation('0 + x'),
       pyblp.Formulation('0 + x + z')
   ),
   beta=[1, -2, 2],
   sigma=1,
   gamma=[1, 4],
   product_data=id_data,
   integration=integration,
   seed=0
)

**Comment by jeffgortmaker** [comment]
I see. I think you're using a version of the package (may just be the latest version on pip) where prices and shares are initialized as zero as a placeholder until they can be replaced by `Simulation.solve`. So this gives the error.

I've overhauled the `Simulation` class recently (actually in response to #29 that you brought up). This should no longer be a problem in the dev version of the code where prices and shares are initialized as (nonzero) draws from uniform distributions.

Note that my original thoughts about including logs still might be an issue for you.
