### ISSUE TITLE
costs_type on version 0.8.0

### ISSUE THREAD

**Issue by maduartefilho** [jeffgortmaker/pyblp#40]
I am trying to reproduce the "Random Coefficients Logit Tutorial with the Automobile Data" from the package documentation using version 0.8.0, but the 'solve' function does not recognize the 'costs_type' argument. The code run if I drop 'costs_type'. Is this a bug? Or the package does not support more 'costs_type'?

Thank you

**Comment by jeffgortmaker** [comment]
The `costs_type` argument was moved into `Problem` in 0.8.0. Looks like the stable version of the docs haven't updated yet (I just released the new version) -- I'll look into that. Until then, I'd suggest using the dev version of the docs: https://pyblp.readthedocs.io/en/latest/_api/pyblp.Problem.html

**Comment by jeffgortmaker** [comment]
Just updated the stable docs, so those should reflect the 0.8.0 changes as well.
