### ISSUE TITLE
Documentation: in the ProblemResults class, what is the ordering of "delta"?

### ISSUE THREAD

**Issue by flynnzac** [jeffgortmaker/pyblp#41]
In the ProblemResults part of the documentation, it does not mention what the ordering of the mean utility's is (unless I'm misreading). Is it delta(firm1, market1), delta(firm2, market1), ..., delta(firm1, market2), ... or is it market increments first and then firm?

**Comment by jeffgortmaker** [comment]
The ordering is the same as the ordering that you gave in `product_data` -- there's no sorting.
