### ISSUE TITLE
Subtracting contributions of linear gamma parameters in theta from iv_delta instead of iv_tilde_costs

### ISSUE THREAD

**Issue by douglascturner** [jeffgortmaker/pyblp#42]
https://github.com/jeffgortmaker/pyblp/blob/ad7e4f65735d56c0ed8830c1df650c1344e21b44/pyblp/economies/problem.py#L672

Unless I'm mistaken, line 672 should read

```

iv_tilde_costs -= self._compute_true_X3(index=~parameters.eliminated_gamma_index.flatten()) @ theta_gamma

```

This is so the contributions of the linear gamma parameters are subtracted from iv_tilde_costs. The contributions of the beta parameters were subtracted from iv_delta on line 669. Apologies if I'm misunderstanding something.

**Comment by chrisconlon** [comment]
Nice find. This looks like a real bug to me.

**Comment by jeffgortmaker** [comment]
Yeah, this is definitely a bug that will impact anyone who doesn't want to concentrate out linear supply-side parameters (e.g., to bound them). Thanks for pointing it out.
