### ISSUE TITLE
Computing shares after a change in exogenous variable

### ISSUE THREAD

**Issue by bshiller** [jeffgortmaker/pyblp#43]
Hello,

I have been trying to simulate shares under a counterfactual where ONLY one of the exogenous variables changes.  I can't seem to get it to work with the ProblemResults.compute_shares function (it seems that it doesn't register a change in product_data, it must have the product data stored somewhere I can't see).  When I tried using the simulation class, it appears to simulate not only shares, but also prices (which I don't want).  I was wondering if there is any way to resimulate counterfactuals shares under a scenario where only one of the exogenous variables changes (keeping prices the same).

**Comment by jeffgortmaker** [comment]
I think you've almost got it. You should definitely be using the `Simulation` class when doing counterfactuals that aren't explicitly supported by `ProblemResults`.

To keep prices the same, pass the prices you want to the `prices` argument of `Simulation.replace_endogenous` and set `iteration=Iteration('return')`. This just uses the iteration "routine" that simply returns the the starting values, which are `prices`. You can verify that prices haven't changed by looking at the `product_data` attribute of the returned simulation results.

**Comment by bshiller** [comment]
Jeff, Thanks so much!

**Comment by fpinter** [comment]
Jeff, can you add this to the documentation somewhere?

> To keep prices the same, pass the prices you want to the `prices` argument of `Simulation.replace_endogenous` and set `iteration=Iteration('return')`. This just uses the iteration "routine" that simply returns the the starting values, which are `prices`. You can verify that prices haven't changed by looking at the `product_data` attribute of the returned simulation results.

**Comment by jeffgortmaker** [comment]
Yeah for sure, good point.

**Comment by jeffgortmaker** [comment]
(Added in 51433dc)
