### ISSUE TITLE
knitroNumPy is now in examples/Python/build/lib/knitro/numpy instead of examples/Python. Version 12 also calls a wrapper and ktr to verify license and for backwards compatibility. Simplest solution may be an if/else on knitro.__version__ to load knitro.numpy or knitroNumPy.

### ISSUE THREAD

**Issue by bshiller** [jeffgortmaker/pyblp#45]
By any chance do you have some code solving this issue that you could post?  

knitroNumPy is now in examples/Python/build/lib/knitro/numpy instead of examples/Python. Version 12 also calls a wrapper and ktr to verify license and for backwards compatibility. Simplest solution may be an if/else on knitro.__version__ to load knitro.numpy or knitroNumPy.

I'll report back on other alternatives if I can find one.

Thanks!

_Originally posted by @kw468 in https://github.com/jeffgortmaker/pyblp/issues/33#issuecomment-503282711_

**Comment by jeffgortmaker** [comment]
Can you try using the dev version of the code (i.e., cloning this repo and importing `pyblp` from the cloned repo) and see if it then works with v12?

I think I added v12 support in a recent commit, but I haven't released a new stable version to pypi/pip since then.

**Comment by bshiller** [comment]
Thanks!!!  Seems to be working.
