### ISSUE TITLE
Display results at each iteration

### ISSUE THREAD

**Issue by xiaoxizhao** [jeffgortmaker/pyblp#47]
Hi,
I am estimating a large model and want to monitor the optimization process. Thus, I am wondering is there any option to display results at each iteration, during (not after) the optimization? The analogue option in MATLAB, for example, is 
"options = optimoptions(@fminunc,'Display' , 'iter');"

Thanks you!

**Comment by jeffgortmaker** [comment]
I'd take a look at [`pyblp.options`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.options.html).

By default results are outputted every iteration, unless you've disabled this behavior with `pyblp.options.verbose = False`, like we do in most of the tutorials.

PyBLP outputs this information to standard output, but if you want to also log it to a file, you can handle its output with `pyblp.options.verbose_output`.

**Comment by xiaoxizhao** [comment]
Thank you very much for you reply. That is exactly what I am looking for.
