### ISSUE TITLE
could not  change the firm_ids and ownership when calculating marginal costs!

### ISSUE THREAD

**Issue by hejiajun100** [jeffgortmaker/pyblp#48]
API : ProblemResults.compute_costs(firm_ids=None, ownership=None, market_id=None)
1. I did not include firm_ids in the product_data, but using results.compute_costs could still calculate the marginal costs. The API documentation says you must include firm_ids field before calculating marginal costs. so why could it work without firm_ids?
2. After estimation,  I try to use ProblemResults.compute_costs(firm_ids=None, ownership=None, market_id=None) to calculate the costs, but error shows up, which says that could not find firm_ids in compute_costs(),  there is only market_id in this API?

**Comment by jeffgortmaker** [comment]
Thanks for this - you're right that you must include firm IDs before calculating marginal costs. It's definitely a bug that it "works" regardless (I think ownership matrices of all zeros are being constructed, so these "costs" don't have much meaning). Post-estimation methods that need firm IDs/ownership matrices should raise an exception if they can't find any firm IDs or ownership matrices.

**Comment by hejiajun100** [comment]
Thanks for replying so quickly! There is another problem about this issue. 
After estimation, I try to use ProblemResults.compute_costs(firm_ids=None, ownership=None, market_id=None) to calculate the costs, but error shows up, which says that _compute_costs() got an unexpected keyword argument 'firm_ids'. So how to pass the firm_ids to it?  Besides, I find that including the firm_ids in the product_data or not before estimation gives same marginal costs. Why this could happen?

**Comment by jeffgortmaker** [comment]
Do you have the most recent version of the package (0.9.0)? You can check with `pyblp.__version__`. If so, can you send over the actual code that's giving you an issue? `firm_ids` should be a valid argument to `ProblemResults.compute_costs`.

**Comment by hejiajun100** [comment]
Thanks a lot!
My version is now  0.8.1, so maybe updating the version could help? I will try and report issues if I come across a new one~

**Comment by jeffgortmaker** [comment]
Yes, hopefully that should help. I think I recall that the API changed a version or two ago. Happy to help with any other issues.
