### ISSUE TITLE
Questions about the initial value

### ISSUE THREAD

**Issue by hejiajun100** [jeffgortmaker/pyblp#49]
Hi,
In the tutorial of Nevo, I find that it will yield the same result when I pass different initial value. However, I get different results using my own data. I am asure that nothing but the initial value change. Another weird thing is that when I try to pass the result as the initial value, it return different result instead.  If it return different results, how can I get a robust one?    
Looking for your help~ Thanks

**Comment by jeffgortmaker** [comment]
This question is too general for me to give a specific suggestion - sorry. I recommend reading [our paper](https://jeffgortmaker.com/files/pyblp.pdf) closely and following our recommendations, especially those regarding optimization in section 3.3.

It's important to keep `pyblp.options.verbose = True` and to pay close attention to FOCs and SOCs when looking at optimization results. This will give you a better idea of what's going on. Also keep in mind that two-step GMM requires two rounds of optimization.

**Comment by hejiajun100** [comment]
Ok, I will have a try, thanks!

**Comment by jeffgortmaker** [comment]
Closing this for now to move discussion into the other thread.
