### ISSUE TITLE
Question about the pyblp.build_integration

### ISSUE THREAD

**Issue by hejiajun100** [jeffgortmaker/pyblp#50]
Hi~
It's me again.
1. Does pyblp.build_integration build the same nodes every time?   I use the code below and find that it will yield the same nodes, even when I change the number like 4→6, the first 4 column of nodes are the same as those when the characteristics number is 4. 
Code:    mc_integration = pyblp.Integration('monte_carlo', size=50, specification_options={'seed': 0})
agent_data=pyblp.build_integration(mc_integration,4)
2. If it yiled the same nodes every time I use the Monte_carlo, then why the regression results are different even when I pass the same initial value to the problem.solve

**Comment by jeffgortmaker** [comment]
1. Yes, if you use the same seed, the nodes should always be the same.

2. I don't know without any more information. There could be something else stochastic in your setup. If you can't figure it out, consider posting a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example).

**Comment by hejiajun100** [comment]
Thanks a lot!!!
I don't know how to construct a MWE to express my problem so I upload the related original ipynb files and data, if you have time, I appreciate a lot for your help.
Related files: https://www.lanzous.com/iad7exc
The download button is in Chinese but just click any  orange buttons below, I believe you could get the right files.

**Comment by jeffgortmaker** [comment]
Sorry, I don't have the time to look through all of this. Can you read up on how to construct a MWE? For example, you can read [this page](https://stackoverflow.com/help/minimal-reproducible-example), which gives good guidelines.

If you reduce your problem to as few lines of code as possible (ideally something like 15 lines of code that get different estimates with "identical" runs of the problem) and post it here, I'm happy to take a look.

**Comment by hejiajun100** [comment]
Ok, let me have a try.

**Comment by jeffgortmaker** [comment]
Closing this for now - feel free to re-open.
