### ISSUE TITLE
Estimate supply side with only fixed effects.

### ISSUE THREAD

**Issue by luisarmona** [jeffgortmaker/pyblp#51]
Hello,
I am estimating a BLP model with time-invariant characteristics (besides price) and product fixed effects. Thus, I am estimating only heterogenous taste coefficients for each time invariant characteristic, and a linear parameter in prices. My supply side only includes, as a result, product fixed effects. When I try to feed a formulation for the supply side with only product fixed effects, (e.g. ```supply_formulation = pyblp.Formulation('0',absorb='C(product_id)')```) I receive a Patsy error given from this line of code in `formulations.py`

https://github.com/jeffgortmaker/pyblp/blob/aa25593645e5ca26934a81041c6bb061eb0580aa/pyblp/configurations/formulation.py#L129

Is there a way to estimate such a supply side specification in `pyblp`? I realize I could include indicators for each product_id (e.g. ```supply_formulation = pyblp.Formulation('C(product_id)')```) but this will run much slower/take up more memory since there are many products. I am wondering if there is a fix I am missing that is workable within the existing framework of `pyblp` that will allow me to do this. Thanks for your time.

**Comment by jeffgortmaker** [comment]
Thanks for pointing this out.

Off the top of my head, a quick fix would be to have a supply formulation that consists of a single arbitrary variable (that isn't collinear with product IDs), and to fix its corresponding parameter in gamma to zero. You should be able to do this by specifying `gamma = 0` in `Problem.solve`, but let me know if you have any trouble or if you can think of a simpler workaround?

This is sort of a hackish workaround, so even if this work for you I'll keep this issue open as a reminder to support FE-only matrices. It might require a nontrivial amount of refactoring, so I can't guarantee that it's something I'll do right away.

**Comment by luisarmona** [comment]
@jeffgortmaker thanks! this appears to work computationally, I was thinking a similar solution would hack my way around the problem. Appreciate the quick feedback

**Comment by jeffgortmaker** [comment]
Cleaning up issues, this hasn't come up again and the solution here works fine, so I think I'll leave it as is.
