### ISSUE TITLE
Incorporate Instrument Construction in pyblp.Problem or to_problem() method

### ISSUE THREAD

**Issue by claudiolucinda** [jeffgortmaker/pyblp#52]
Hi,

Maybe I have not understood completely the docs, but why can't we let the instrument construction phase to be done in the pyblp.Problem definition phase? 

All examples (except the one on optimal instruments) seem to get the instruments brought in from the raw data, and there's no method to_problem() for build_blp_instruments and build_differentiation_instruments.

Sorry if the question seems silly.

Best,
Claudio

**Comment by jeffgortmaker** [comment]
Hi Claudio, thanks for the input. I made this choice early on for two reasons:

1. Instruments tend to be application-specific, and
2. Most other statistical computing packages I've seen are structured this way.

Although it's clear to me how a problem should be re-created under an approximation to the optimal instruments, I'd be uncomfortable with functionality that constructs instruments "under the hood" without any user involvement/meditation.

That said, I think constructing instruments with the functions you mentioned and adding these to your dataset can be somewhat cumbersome (even with functions like `pyblp.data_to_dict`), so I'm open to suggestions about how to make this easier, either though new functionality or new tutorials.

Is there anything in particular that you find cumbersome with the current API? (I can think of a lot of things personally, but it's helpful to get feedback on these things.)

**Comment by claudiolucinda** [comment]
Hi Jeff,

Haven't found the data_to_dict method. It seems it helps a lot here - it
would help me, for sure.

I have a couple of suggestions, I think maybe someone else would come up
with the same question:

1) A tutorial for using the build instruments methods to construct the
instruments inside pyblp instead of bringing them in.

2) Maybe adding an option on either problem or problem.solve to let the
user select what sort of "standard" instruments to use.

(1) seems to be way easier than (2) to implement. However, I think there's
some merit on letting the code take care of "plain vanilla" instruments,
only letting the user bring in really application specific instruments.

Hope my suggestions help you!

Best,
Claudio

<Message sent from mobile. Apologies for brevity and typos.>

Em sáb, 28 de mar de 2020 11:37, Jeff Gortmaker <notifications@github.com>
escreveu:

**Comment by jeffgortmaker** [comment]
Thanks! Your suggestions make a lot of sense. Feedback like this is very helpful. At a minimum I'll definitely do (1).

I'll leave this open as a reminder going forward.
