### ISSUE TITLE
Estimation fails without error or warning when using a single instrument

### ISSUE THREAD

**Issue by bardwnb** [jeffgortmaker/pyblp#54]
An odd phenomenon I discovered, which might call for some additional error handling.  I'm using the BLP instruments or differentiation instruments created using pyblp, along with one cost-shifter variable  from my data.  By accident I managed to comment out the code that added the BLP instruments to my  product dataset, so that the only instrument was my single cost-shifter.  The solver ran with no errors or warnings, but terminated on the first GMM step, with the starting parameters for theta as the supposed solution.

This drove me to distraction for a while since I could not figure out why the solver would only give me back my inputs.  As I've been fiddling with my instruments, I've had this happen a few more times, and while now I know what to fix, it's fairly annoying.  It seems like it would make sense to test early in the set-up step whether MD is greater than 1, and exit with an error if not.

Here's an example using the fake cereal data from the tutorial (I'm using pyblp in R via reticulate):

```
library(reticulate)

#Import the pyblp package from python

main<-import_main()
pyblp<-import("pyblp")

#Read in product data; drop all but demand_instruments0
product_data = read.csv(pyblp$data$NEVO_PRODUCTS_LOCATION)
product_data[,12:30]<-NULL

#Configure problem
Int <- pyblp$Integration('product', size=5L)

X1_formulation = pyblp$Formulation('0 + prices', absorb='C(product_ids)')
X2_formulation = pyblp$Formulation('1 + prices + sugar + mushy')
product_formulations = c(X1_formulation, X2_formulation)

problem = pyblp$Problem(product_formulations, product_data, integration=Int)

#Estimate: should return a diagonal matric of 1's for theta
results1 = problem$solve(sigma=matrix(1,nrow=4,ncol=4))
results1
```

**Comment by jeffgortmaker** [comment]
Thanks for the report - I agree that more verbosity here would be helpful.

The best option may be to just output a warning if it looks like the model is under-identified, as in your example. Checking for this is a bit more involved than checking whether MD > 1, so I'll keep this issue open for now as a reminder.

Also: When I ran your example interactively using reticulate, my RStudio console didn't automatically print out things like problem dimensions and optimization progress. Are these things automatically printed out for you? E.g. when you initialize a `Problem` using R, do you get an automatic printout of the problem's dimensions and formulations?

I think this type of information helps people sort through configuration issues. It would be a separate issue if this information wasn't getting automatically printed out for R users.

**Comment by bardwnb** [comment]
Sorry for the slow response.  No, you don't automatically get an automatic printout of the problem when you initialize it.  This is somewhat expected, since R often doesn't print output when you assign an object.

**Comment by jeffgortmaker** [comment]
I see, thanks. This is probably something that I can make better by having a setting that calls `sys.stdout.flush()` whenever something is printed. Until then, you might want to try

```R
sys = import('sys')
sys$stdout$flush()
```

if you expected to see output from a previous command involving pyblp but didn't see any output.
