### ISSUE TITLE
Suggestion: add labels to to_dict method

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#59]
I'm using the following general workflow:

- Script 1: load data, initialize and solve problem, and save outputs to a file with
````
with open(filename, 'wb') as fout:
    pickle.dump(results.to_dict(), fout)
````
- Script 2: load the pickle file and output formatted tables

As far as I can tell, the output of `results.to_dict()` does not contain the labels for the coefficients. This means I have to regenerate the labels in Script 2 and ensure that they line up properly with the outputs from Script 1.

I've figured out a few ways to regenerate the labels without re-solving the problem (`[str(x) for x in formulation._build_matrix(data)[1]]` seems simplest) but they require private methods and re-loading datasets. I'd rather avoid them if I can.

Am I overlooking something? Unless there's a better way, would you consider adding the labels (`results._parameters.beta_labels`, `results._parameters.pi_labels`, etc.) to the output from `results.to_dict()`?

**Comment by jeffgortmaker** [comment]
You're not overlooking anything. Adding labels to `ProblemResults` and the output of `to_dict()` makes a lot of sense from a workflow perspective -- I'll add them. Thanks for the suggestion.
