### ISSUE TITLE
Replicating a ProblemResults object from previous results

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#61]
My general workflow (see #59) is:

1. Initialize and solve Problem, and save outputs to a file
2. Load file and do all post-estimation tasks: calculate elasticities, run counterfactuals, etc.

I'm attempting to recreate the ProblemResults object from the file to calculate elasticities. But I am unable to replicate the original results and I keep getting different `beta` and standard errors. My attempt uses 1-step GMM with the `updated_W` as weight matrix, and `Optimization('return')`, but the results are still different.

An example using the Nevo tutorial:
````
import pyblp
import numpy as np
import pandas as pd

product_data = pd.read_csv(pyblp.data.NEVO_PRODUCTS_LOCATION)
product_formulations = (
    pyblp.Formulation('0 + prices', absorb='C(product_ids)'),
    pyblp.Formulation('1 + prices + sugar + mushy'))
mc_integration = pyblp.Integration('monte_carlo', size=50, specification_options={'seed': 0})
mc_problem = pyblp.Problem(product_formulations, product_data, integration=mc_integration)
bfgs = pyblp.Optimization('bfgs', {'gtol': 1e-4})
results3 = mc_problem.solve(sigma=np.eye(4), optimization=bfgs)
results3_dict = results3.to_dict()

results3_new = mc_problem.solve(sigma=results3_dict['sigma'],
                                optimization=pyblp.Optimization('return'),
                                W=results3_dict['updated_W'], method='1s')
````

The two ProblemResults objects agree on `sigma` but nothing else:
````
results3_new.sigma - results3.sigma
Out[4]: 
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

results3_new.sigma_se - results3.sigma_se
Out[5]: 
array([[-1.57204003e-05,             nan,             nan,
                    nan],
       [            nan, -3.61719537e-05,             nan,
                    nan],
       [            nan,             nan, -6.01722696e-07,
                    nan],
       [            nan,             nan,             nan,
        -3.36885771e-05]])

results3_new.beta - results3.beta
Out[6]: array([[-0.00354318]])

results3_new.beta_se - results3.beta_se
Out[7]: array([[-1.34498139e-05]])
````

Am I doing this incorrectly, or is this in general not possible? And if this is not possible, is there a way to get the elasticities without re-running the full optimization?

**Comment by jeffgortmaker** [comment]
You should be using [`W`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.ProblemResults.html#pyblp.ProblemResults.W), not `updated_W` if you want to obtain the same results. More generally, here's how I'd obtain the same results:

```python
results3_new = mc_problem.solve(
    sigma=results3_dict['sigma'],
    beta=results3_dict['beta'],
    delta=results3_dict['delta'],
    W=results3_dict['W'],
    optimization=pyblp.Optimization('return'),
    iteration=pyblp.Iteration('return'),
    method='1s',
)
```

This gives precisely the same point estimates, and the same standard errors up to some mysterious numerical error. If you have `gamma` or `pi`, you'd include them here as well.

I'd also note that `check_optimality='gradient'` will avoid re-computing the Hessian, which is the thing that'll take the longest here.

**Comment by fpinter** [comment]
Perfect, thanks! That works for me. (The mysterious numerical error seems to go only in one direction, oddly, and while it's not large, it's not exactly small either.)

**Comment by fpinter** [comment]
How would one do this with optimal instruments? Since the instruments aren't kept, setting up the problem is no longer trivial. For example, replace the line that starts with `results3` with

````
results3 = (mc_problem
            .solve(sigma=np.eye(4), optimization=bfgs)
            .compute_optimal_instruments()
            .to_problem()
            .solve(sigma=np.eye(4), optimization=bfgs))
````

**Comment by jeffgortmaker** [comment]
Yeah you're probably going to have to save the updated instruments if you don't want to re-compute them.

The simplest way to do this is to save `results3_dict['ZD'] = results3.problem.products.ZD` and when re-creating your `mc_problem`, use `results3_dict['ZD']` as your `demand_instruments`, and set `add_exogenous=False`. Note that `results3_dict['ZD']` will already have `product_ids` absorbed; this is fine.

**Comment by jeffgortmaker** [comment]
Related to this, 508fd9b should make `ProblemResults` and other objects work with pickling. So hopefully all of this should be easier going forward, and you can use fewer `'return'` tricks.

**Comment by fpinter** [comment]
From your previous comment, I know this is a moot point in the development version. But I wanted to flag that, if income is involved, the new and old ProblemResults objects seem to give different elasticities. To replicate (note, though, that the BLP tutorial doesn't converge properly on my machine)

````
product_data = pd.read_csv(pyblp.data.BLP_PRODUCTS_LOCATION)
agent_data = pd.read_csv(pyblp.data.BLP_AGENTS_LOCATION)
product_formulations = (
   pyblp.Formulation('1 + hpwt + air + mpd + space'),
   pyblp.Formulation('1 + prices + hpwt + air + mpd + space'),
   pyblp.Formulation('1 + log(hpwt) + air + log(mpg) + log(space) + trend')
)
agent_formulation = pyblp.Formulation('0 + I(1 / income)')
problem = pyblp.Problem(product_formulations, product_data, agent_formulation, agent_data, costs_type='log')
initial_sigma = np.diag([3.612, 0, 4.628, 1.818, 1.050, 2.056])
initial_pi = np.c_[[0, -43.501, 0, 0, 0, 0]]
results = problem.solve(
    initial_sigma,
    initial_pi,
    costs_bounds=(0.001, None),
    W_type='clustered',
    se_type='clustered',
    initial_update=True,
)

results_dict = results.to_dict()
results3_new = problem.solve(
    sigma=results_dict['sigma'],
    beta=results_dict['beta'],
    pi=results_dict['pi'],
    gamma=results_dict['gamma'],
    delta=results_dict['delta'],
    W=results_dict['W'],
    optimization=pyblp.Optimization('return'),
    iteration=pyblp.Iteration('return'),
    method='1s',
    check_optimality='gradient'
)

elast1 = results3.compute_elasticities()
elast2 = results3_new.compute_elasticities()
````

The `elast1` and `elast2` arrays are different. They have different shapes:
````
elast1.shape
Out[8]: (2256, 24)

elast2.shape
Out[9]: (2217, 150)
````
And the numbers are also just different.

**Comment by jeffgortmaker** [comment]
Where did `results3` come from? It has the same N = 2256 as the cereal data, while the other results has the N = 2217 of the automobile data that you loaded. (Coincidentally these N's are very close to one another.)

**Comment by fpinter** [comment]
Oops. That was dumb. Thanks for catching.

I am encountering an odd error with my data where elasticities don't replicate after this save-and-restore process. But I am not able to replicate on the autos data.

**Comment by jeffgortmaker** [comment]
Hm strange. If you manage to get an example that you can share, happy to take a look. This is after pickling a ProblemResults object, or with the old save-and-restore process?

**Comment by fpinter** [comment]
Will do! This is with the old save-and-restore process.
