### ISSUE TITLE
any help would be appreciated

### ISSUE THREAD

**Issue by iovoifaith** [jeffgortmaker/pyblp#70]
Hi, I'm new to python. Sorry if this is a naive question.
I tried to apply my own data but I always get the result that suggests the number of optimization iteration is zero and thus sigma is just the starting value.
Any idea why this happens?
Thanks ahead!
[zero iteration.pdf](https://github.com/jeffgortmaker/pyblp/files/5324874/zero.iteration.pdf)

**Comment by iovoifaith** [comment]
I kind of figured it out now and think it was related to not have "demand_instrument0"....

**Comment by jeffgortmaker** [comment]
Glad you worked it out, starting matrices at e.g. 1 is a common issue -- hopefully the warning message I added after #62 helped out.
