### ISSUE TITLE
Matrix dimensions in background.rst

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#72]
The definition of Y(θ) in https://github.com/jeffgortmaker/pyblp/blob/master/docs/background.rst#the-objective seems off. In particular, since the left hand side is a column vector, Y(θ) should be a 2N x 1 column vector, but it's instead defined as a diagonal matrix.

**Comment by jeffgortmaker** [comment]
Ah yep, I think I just copied the other matrices without editing it - thanks.
