### ISSUE TITLE
Reserved Names

### ISSUE THREAD

**Issue by cpfiffer** [jeffgortmaker/pyblp#74]
I was unable to find a list of reserved variable names -- is there something like that prepped somewhere?

**Comment by jeffgortmaker** [comment]
For `product_data` it should be all the attributes of [`Products`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Products.html). Were you getting an error message something like "These reserved names in product_formulations are invalid"? I should probably make that more explicit.

**Comment by cpfiffer** [comment]
No, no error as of yet. Just doing some data prep and trying to figure out exactly which things I need and what names to use exactly. 

That more or less answers my question, thanks!
