### ISSUE TITLE
In what order are markets stacked?

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#75]
The docs for `pyblp.ProblemResults.compute_consumer_surpluses` say:
> By default, consumer surpluses are computed in all markets and stacked.

In what order are the results returned? Sorted by market id? In the order of appearance in `product_data`? The order of appearance of `agent_data`? Or something else?

**Comment by fpinter** [comment]
I guess my question really is, how is the order of `Problem.unique_market_ids` determined?

**Comment by jeffgortmaker** [comment]
> If market_ids was not specified, rows are in the same order as Problem.unique_market_ids.

And `Problem.unique_market_ids` are sorted by `np.unique` I believe. In retrospect the docs don't make it 100% clear that if you specify `market_ids`, surpluses will be returned in that same order.

If you want to double-check that you've got the ordering right, you can also call the function market-by-market.
