### ISSUE TITLE
ProblemResults methods, but for SimulationResults

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#79]
I would like to run a complex simulation and then use the convenient `ProblemResults` methods (`compute_profits`, etc.) on the output. Jeff, I think you mentioned at some point that this was on your list, but lower priority. Think of this issue as a feature request.

The code below is (approximately) what I'm doing now; is this the right way to go about it? (This is for a counterfactual where one product is dropped and prices adjust.)

````
import pyblp
import pandas as pd

# Get estimates
product_data = pd.read_csv(pyblp.data.NEVO_PRODUCTS_LOCATION)
product_formulation = pyblp.Formulation('0 + prices + C(product_ids)')
problem = pyblp.Problem(product_formulation, product_data)
results = problem.solve()

# Drop product
DROP = 'F1B06'
product_data_new = product_data[product_data['product_ids'] != DROP]
xi_new = results.xi[product_data['product_ids'] != DROP]
beta_new = [b for b, label in zip(results.beta, results.beta_labels)
            if label != f"product_ids['{DROP}']"]
costs_new = results.compute_costs()[product_data['product_ids'] != DROP]

# Simulate counterfactual
sim = pyblp.Simulation(product_formulation, product_data_new,
                       beta=beta_new, xi=xi_new)
sim = sim.replace_endogenous(costs=costs_new)

# Convert back to ProblemResults and get profits
sim_problem = sim.to_problem(product_data=product_data_new)
sim_results = sim_problem.solve(beta=beta_new,
                                optimization=pyblp.Optimization('return'),
                                iteration=pyblp.Iteration('return'),
                                method='1s')
print(sim_results.compute_profits())
````

**Comment by jeffgortmaker** [comment]
Yes, this is exactly how I'd currently do it. Of course if you're only interested in profits you should be able to figure those out from `sim`, but I'm guessing you also want things like elasticities.

And yeah, making this more convenient (e.g. with a `SimulationResults.to_problem_results()` method) is on my radar -- I'll keep this open as a reminder -- thanks.

**Comment by fpinter** [comment]
Oh, one thing I'm not sure about. Should the line
````
sim_problem = sim.to_problem(product_data=product_data_new)
````
be changed to
````
sim_problem = sim.to_problem(product_data=sim.product_data)
````
to use the updated prices and shares?

**Comment by jeffgortmaker** [comment]
Ah I didn't catch that. Yeah, you were overriding the updated prices and shares by passing `product_data`. By default, that argument in [`SimulationResults.to_problem`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.SimulationResults.to_problem.html) uses `SimulationResults.product_data`, which has the updated shares. So you can just do `sim_problem = sim.to_problem()`.

If you wanted anything other than what's in `sim.product_data` (e.g. some other instruments), I would just update your `product_data_new` with the updated prices/shares, and initialize your `Problem` like normal.

**Comment by fpinter** [comment]
Thanks. In this particular example if I do `sim_problem = sim.to_problem()` I get a collinearity error. So I guess this is a hack to suppress the default instruments, which (for some reason) are collinear.

**Comment by jeffgortmaker** [comment]
Yeah, the default instruments are "sums of characteristic" BLP instruments, but there isn't much checking for collinearity, e.g. of sums of the constant term when you have something like a balanced panel.

**Comment by fpinter** [comment]
In random coefficients or demographics specifications, I haven't been able to replicate the original results exactly (even when I don't change anything). See below (apologies for long paste). Am I missing something simple?

````
import pyblp
import numpy as np
import pandas as pd

# Get estimates
product_data = pd.read_csv(pyblp.data.NEVO_PRODUCTS_LOCATION)
agent_data = pd.read_csv(pyblp.data.NEVO_AGENTS_LOCATION)
product_formulation = (pyblp.Formulation('0 + prices + C(product_ids)'),
                       pyblp.Formulation('1 + prices + sugar + mushy'))
agent_formulation = pyblp.Formulation('0 + income + income_squared + age + child')
problem = pyblp.Problem(product_formulation, product_data,
                        agent_formulation, agent_data)
results = problem.solve(sigma=np.diag([ 0.55855527,  3.31769016, -0.0058    ,  0.09384918]),
                        pi=np.array([[ 2.29539887e+00,  0.00000000e+00,  1.28393713e+00, 0.00000000e+00],
                                     [ 5.89984774e+02, -3.02789065e+01,  0.00000000e+00, 1.10494057e+01],
                                     [-3.85661091e-01,  0.00000000e+00,  5.23056096e-02, 0.00000000e+00],
                                     [ 7.45463669e-01,  0.00000000e+00, -1.35230031e+00, 0.00000000e+00]]),
                        optimization=pyblp.Optimization('l-bfgs-b', {'gtol': 1e-15}),
                        method='1s')

# Simulate counterfactual
sim = pyblp.Simulation(product_formulation, product_data,
                       agent_formulation=agent_formulation,
                       agent_data=agent_data,
                       beta=results.beta, xi=results.xi,
                       sigma=results.sigma, pi=results.pi)
sim = sim.replace_endogenous(prices=product_data['prices'],
                             costs=np.zeros(product_data.shape[0]),
                             iteration=pyblp.Iteration('return'))

# Convert back to ProblemResults and get profits
sim_problem = sim.to_problem(product_data=sim.product_data) # avoid collinearity error
sim_results = sim_problem.solve(beta=results.beta,
                                sigma=results.sigma,
                                pi=results.pi,
                                optimization=pyblp.Optimization('return'),
                                iteration=pyblp.Iteration('return'),
                                check_optimality='gradient',
                                method='1s')
print(results.xi - sim_results.xi)
print(results.compute_consumer_surpluses() - sim_results.compute_consumer_surpluses())
print(results.compute_elasticities() - sim_results.compute_elasticities())
````

**Comment by jeffgortmaker** [comment]
I think you're missing `sim_problem.solve(..., delta=results.delta)`. Otherwise the mean utility is initialized as the solution to the simple logit problem.

**Comment by fpinter** [comment]
Thanks, that was exactly it.

**Comment by jeffgortmaker** [comment]
Forgot about this issue -- I added ProblemResults methods to SimulationResults in 9fda5b4720185191519284ff952abdb13f6e4e80. They're in the dev version of the code and will be included in the next stable release.
