### ISSUE TITLE
Modifications to the standard BLP utility function: incorporating customer location data

### ISSUE THREAD

**Issue by adrukker** [jeffgortmaker/pyblp#81]
I have some unique data on the home location of customers that I'd like to incorporate into my demand estimation. I'm interested to see how driving distance to the product affects utility. Incorporating such data requires a slight modification to the utility function and market shares equations, whereby you integrate over the distribution of customer locations. 

A simple BLP-type logit utility function (without random coefficients) takes the form:

U<sub>ijt</sub> = &delta;<sub>jt</sub> + &varepsilon;<sub>ijt</sub>

with corresponding market shares:

s<sub>jt</sub> = exp(&delta;<sub>jt</sub>) / &sum;<sub>j'</sub> exp(&delta;<sub>j't</sub>)

A term representing driving distance can be incorporated like so:

U<sub>ijtl</sub> = &delta;<sub>jt</sub> + &tau;d<sub>jl</sub> + &varepsilon;<sub>ijt</sub>

where d<sub>jl</sub> is the driving distance from location l to product j, so that U<sub>ijtl</sub> is the utility of customer i who lives in location l in market t who choses product j. Since &varepsilon;<sub>ijt</sub> is distributed Extreme Value Type-I, the corresponding probability that a customer from location l purchases product j is:

s<sub>jtl</sub> = exp(&delta;<sub>jt</sub> + &tau;d<sub>jl</sub>) / &sum;<sub>j'</sub> exp(&delta;<sub>j't</sub> + &tau;d<sub>jl</sub>)

The market share for product j in market t is then found by aggregating the choice probabilities over the distribution of home locations l:

s<sub>jt</sub> = &sum;<sub>l</sub> &iota;<sub>l</sub> &times; s<sub>jtl</sub>

where &iota;<sub>l</sub> is the probability mass of consumers in location l. Then estimation proceeds as usual. The coefficient of interest is &tau;, the disutility of driving.

I'm wondering if pyblp currently supports such a modification. Thank you in advance for any assistance.

**Comment by jeffgortmaker** [comment]
Yes, although with some caveats. See @chrisconlon's [response to a similar question](https://github.com/jeffgortmaker/pyblp/issues/57#issuecomment-628076509).

If your observed shares are at the `jt` level, you should be able to model this with  `Pi` parameters on either (a) store dummies in `X2` interacted with distances in `d`, or (b) distances in `X2` interacted with location dummies in `d`. The caveat is that you'd need one parameter per (a) store or (b) location --- we don't currently support parameter restrictions or product-specific demographics.

**Comment by chrisconlon** [comment]
The main issue here is whether the s_jtl is observed.

If yes, then (j,t,l) is a market and you're good to go.

If no, (which is I think the case) then you only observe data at the s_jt level then Jeff is correct and the only way to do this in PyBLP right now is to treat "L" as "demographics".

The challenge is figuring out the arbitrary aggregation rule from geographies "L" to markets "T".

I have a student with similar data so this is a common-ish problem -- but I am not sure what the all-purpose solution would be here.

**Comment by adrukker** [comment]
@jeffgortmaker and @chrisconlon,

Thank you both for these very helpful suggestions. I’ve been implementing Jeff’s suggestion with modest success, but maybe Chris’s could work for my data. 

I have quantity data at the (j,l) level. Allow me sidestep the challenge of figuring out the aggregation rule from geographies to markets and assume I have correctly defined the relevant market. Thus, I can construct market shares at the (j,t,l) level. 

I was previously hesitant to run the analysis at the (j,t,l) level for a few reasons. For one, the number of l’s is quite large, e.g. all ZIP Codes in the US. Previously I was aggregating ZIP Codes into a collection of metropolitan areas which constituted the relevant market, and treating the distances traveled as a demographic. Disaggregating to the ZIP Code level would increase the number of markets considerably. But maybe I should not be concerned about this, and PyBLP can easily handle a very large number of markets (conditional on an appropriate amount of computing power on my end). 

My second concern with using data at the (j,t,l) level is the presence of a large number of 0% market shares. The main reason for this is that the outside option’s share is very high (often above 99%). Again, let’s assume I am correctly defining the relevant market, and that the outside option’s share truly is 99% or above in some cases. Should these 0% market share be cause for concern? Strictly speaking, the 0% market shares are inconsistent with the BLP framework, which papers such as [Dube, Hortacsu, and Joo](https://repec.bfi.uchicago.edu/RePEc/pdfs/BFI_WP_202013.pdf) and [Gandhi, Lu, and Shi](https://www.ssc.wisc.edu/~xshi/research/gandhi_lu_shi.pdf) have attempted to solve. 

I want to take advantage of my very granular data but defining the market too granularly will tend to produce 0% market shares, meaning I might not be able to take advantage of the richness of my data. 

Thanks for any additional suggestions, I really appreciate your time. 
-Austin

**Comment by jeffgortmaker** [comment]
Your first concern about many markets is definitely something that PyBLP is designed to handle. And if you run into trouble, I'm sure there are solutions we could hash out.

Your second concern about zero shares seems like the main issue. I'd usually point to some papers that describe this better than I can, but you've already linked to them. More generally, sampling error in market shares has always seemed to me like the Achilles' heel of BLP-type estimation, and small market sizes / zero market shares suggest that you have good reason to worry about this.

We haven't yet added any support for methods that explicitly deal with zeros, etc. So if you wanted to be confident in your (j, t, l) level estimates it sounds like you'd have to implement one of the above procedures yourself.

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to re-open or keep commenting if you have more questions.

**Comment by jeffgortmaker** [comment]
Following up on the original question about location data, fb72dcf9e61c154d7a149e84eb4c507489e5c64e adds support for product-specific demographics to the dev version of the code (still needs some testing, but it should work as-is), which should help with incorporating location data. The end of the [dev documentation](https://pyblp.readthedocs.io/en/latest/_api/pyblp.Problem.html) for `agent_data` has more details on how to specify product-specific demographics.
