### ISSUE TITLE
Using Micro Moments with Simulations

### ISSUE THREAD

**Issue by Joribarash** [jeffgortmaker/pyblp#82]
Is there a way to compute micro moment values from simulation results to feed into a problem formulation? More generally, do simulation results include agent-level product choices? As a side note, if there is any example/testing code using micro moments, that would be extremely helpful for understanding the syntax.

**Comment by jeffgortmaker** [comment]
You can compute "true" micro moment values with [`SimulationResults.compute_micro_values`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.SimulationResults.compute_micro_values.html#pyblp.SimulationResults.compute_micro_values). Your best bet for simulating choices is to use `SimulationResults.to_problem`, "solve" the problem with true parameter values and `optimization=pyblp.Optimization('return')`, and get choice probabilities from `ProblemResults.compute_probabilities`. 

At the moment, micro moments are still in "beta" in the sense that @chrisconlon and I are currently working on them, and their API is changing a bit from version to version. So to simplify our own Monte Carlos, I may end up adding some `SimulationResults` methods that, e.g. simulate agent choices. If you let me know what type of functions would help with your own research, I'd be happy to try to accommodate those too!

At the moment we don't have any micro moment tutorials in the docs, but this is very high on our to-do list whenever we get some time to work on them. Until then, happy to answer questions here too.

**Comment by Joribarash** [comment]
Thank you! Is there a way to bypass the Bertrand game and get from the simulation class to the simulation results class? I'm not sure I understand the simulation class output and why shares are necessarily inconsistent with parameters, given product characteristics that might be out of equilibrium. However, it does seem like simulation class shares are independent of product characteristics.

In my setting, price is not observed and assumed constant, and all product characteristics of interest are exogenous. I tried replace_exogenous() with a X1-only parameter that I simulated outside of pyBLP (basically a collapsed product fixed effect), but I get the following error.
```
Replacing exogenous product characteristics ...
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-47-7c02d9c28db9> in <module>
----> 1 simulation_results = simulation.replace_exogenous(X1_name="f_delta")
      2 simulation_results

/opt/anaconda3/lib/python3.8/site-packages/pyblp/economies/simulation.py in replace_exogenous(self, X1_name, X3_name, delta, iteration, fp_type, shares_bounds, error_behavior)
    798         for t, (delta_t, tilde_costs_t, iteration_stats_t, errors_t) in output_progress(generator, self.T, start_time):
    799             true_delta[self._product_market_indices[t]] = delta_t
--> 800             true_tilde_costs[self._product_market_indices[t]] = tilde_costs_t
    801             iteration_stats[t] = iteration_stats_t
    802             errors.extend(errors_t)

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```
In general, do you think my type of setting can fit with pyBLP? The micro moments functionality would be great since I only observe demographics of agents that choose the inside option, demographic data is often missing, and there are many similar products, so mixed logit would be challenging.

For reference, this is my simulation based on [this](https://drive.google.com/drive/folders/1q-hgaCwfynDd6QnnlfAZTWpGU6erK2T_?usp=sharing) data:
```
import pyblp
import numpy as np
import pandas as pd
product_data = pd.read_csv("Output/Test/Simple Product Data.csv")
agent_data = pd.read_csv("Output/Test/Simple Agent Data Long.csv")
simulation = pyblp.Simulation(
    product_formulations=(
        pyblp.Formulation('0 + f_delta + prices + risk + policy'),
        pyblp.Formulation('0 + risk + policy')
    ),
    agent_formulation=pyblp.Formulation('0 + wnh + comorb + income + male + over65'),
    beta=[1, 1, -2, -1],
    sigma=np.array([
        [0.1,0],
        [0,0.1]
]),
    pi=np.array([
        [0.50,1.50,0.25,-0.15,0.05],
        [0.25,0.50,0.15,-0.05,0.01]
]),
    product_data=product_data,
    xi=np.random.normal(0,0.25,product_data.shape[0]),
    agent_data=agent_data,
    seed=0
)
```

**Comment by jeffgortmaker** [comment]
The easiest way to bypass the Bertrand game is by following the first note on the page for [`Simulation.replace_endogenous`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Simulation.replace_endogenous.html). If you fix prices, `Simulation.replace_endogenous` will just compute your typical multinomial logit shares. The shares (and prices) simulated when initializing a `Simulation` are just arbitrary uniform draws, with the idea that they'll be replaced by e.g. this method.

I'm not sure why you're getting that error with `Simulation.replace_exogenous`. Might just be a bug that I have to look into -- no one really uses that method so I'm not surprised it has a few kinks to work out.

If you think that your setting has market shares observed with very little sampling error, then a BLP-type approach might still make sense. You just wouldn't have to worry about instruments for price endogeneity. Although you'd still need instruments to deal with joint determination of market shares and unobserved quality (see e.g. Gandhi and Houde 2019).

I agree that micro moments should be useful when you have micro data for only parts of the demand system. Of course you'll still need market shares and characteristics for the other parts, including the outside share. If you don't have nice market shares, a more traditional mixed logit approach might be more appropriate.

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to re-open or keep commenting if you have more questions.
