### ISSUE TITLE
Use warnings library for warnings

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#83]
I often keep `pyblp.options.verbose = False` when I'm doing repeated simulations, because it clogs up stdout. But that means I also miss warnings, like the one you (helpfully) implemented in 63c809d. Would it be possible to implement warnings using [Python's warning framework](https://www.python.org/dev/peps/pep-0230/#motivation)? That way they get sent to stderr (instead of stdout) or another place I choose, and also `pyblp.options.verbose` doesn't shut them off.

This is not a high-priority item, but I thought I'd put it here in case others might also want it.

**Comment by jeffgortmaker** [comment]
Yeah that's a great suggestion, thanks. I'll keep it open for when I have a chance.
