### ISSUE TITLE
How to keep observation with zero share?

### ISSUE THREAD

**Issue by TomDvok** [jeffgortmaker/pyblp#86]
As I understand, I cannot estimate BLP model if one or more observations have zero shares (e.g. product was not yet placed on the market at time t). The entire product is removed and the model is then estimated on the rest of sample. 

Is there any way around that doesn't include removal of the entire product/market? I was thinking about replacing zero shares with reasonably small number, however, this doesn't seem legitimate to me.

**Comment by jeffgortmaker** [comment]
Right, zero market shares (and sampling error in market shares more generally) are sort of the Achilles' heel of BLP-type estimation. If this is a serious problem, there are no "good" solutions that I'm aware of with the functionality offered  by PyBLP.

There are, however, alternative estimators that have been developed recently, aimed specifically towards this type of problem. I'll point you to the discussion at the end of #81. The papers referenced there have great discussions of precisely the problem you're dealing with.

**Comment by chrisconlon** [comment]
I think this might be easier than you think.

These models distinguish between a product that isn't available and one
that doesn't sell.

If I have 3 products and 3 periods -- and product 3 is only available in
periods (2,3) then this is fine. I simply don't have an observation for
period 1 and product 3 in my dataset. Don't create an observation for zero
sales.

**Comment by jeffgortmaker** [comment]
I'm going to close this for now, but feel free to re-open/keep commenting if you have more questions.
