### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Tarbo** [jeffgortmaker/pyblp#91]
The word **include**  has redundancy in this [page](https://pyblp.readthedocs.io/en/stable/_notebooks/api/formulation.html). I have also attached a screenshot with the redundancy highlighted.
![Scree shot attached](https://user-images.githubusercontent.com/9603113/124865033-f0e43a00-df87-11eb-81b0-937ef59755ff.png)

**Comment by jeffgortmaker** [comment]
Thanks!
