### ISSUE TITLE
Extract Diagonal for a specified market matrix

### ISSUE THREAD

**Issue by Tarbo** [jeffgortmaker/pyblp#92]
Since elasticities can be computed with a specified market which returns the matrix of `product_ids` by `product_ids`, I think it makes sense to provide an option in the extract diagonal method to work on both stacked (all markets) and non-stacked (a single market) matrices. This saves time from computing elasticities for all markets and passing them via the `extract_diagonal` method when I can just supply elasticities from the single market directly to the `extract_diagonal` method.

**Comment by jeffgortmaker** [comment]
That makes sense, thanks. I'll put adding a `market_id` argument to the `ProblemResults.extract_*` methods on my to-do list.
