### ISSUE TITLE
Calculating delta from estimated parameters

### ISSUE THREAD

**Issue by Harveyt47** [jeffgortmaker/pyblp#96]
Hi, your library is really amazing. 

I was wondering if anyone might be able to help me understand how this library calculates the delta of a product in a given market using the estimated parameters. 

When I use the estimated parameter (beta) in the [nested logit tutorial](https://pyblp.readthedocs.io/en/stable/_notebooks/tutorial/logit_nested.html#Setting-Up-the-Problem) to calculate the delta myself (using delta = beta*prices)  I'm getting different results to when I call `logit_results.delta`. 

Is this because of the unobserved heterogenous product characteristics isn't being taken into account? If so how does the library take this into account?

Thank you for any help

**Comment by jeffgortmaker** [comment]
Yes, this is because `delta = beta * prices` isn't taking into account `xi`, unobserved product quality. (Actually, the tutorial you linked to also takes into account product fixed effects, which you can either think of as separate dummies in X1, or as part of `xi`, as we do in [this notation](https://pyblp.readthedocs.io/en/stable/background.html#fixed-effects).)

Depending on the model, the library uses different variants of the so-called [Berry (1994)](https://www.jstor.org/stable/2555829) inversion. I recommend taking a look at that paper, in particular Section 4, and the nested logit example in Section 5.

**Comment by Harveyt47** [comment]
Having read Berry 1994. I’m still a little confused as to the calculation of delta from estimated parameters. 
I’ll just say where I understand up to, using the simplest problem in the tutorial, the logit model which berry shows as an example in section 4. 
We can calculate delta from the observed market shares. Then using this delta we can estimate the parameters.
`delta_jt = beta*price_jt + xi_jt` 
Because there are no nonlinear parameters here nonlinear optimization is unneeded.

In Berry he treats `xi_jt` as an error term. 
So I guess my question is in calculating delta from the estimated parameters, how do you estimate xi_jt. 

I get you calculate it from 
`xi_jt = delta_jt – beta_hat*price_jt`
Where delta here is observed data

But if say you have a new good entering then the estimated parameters are what we use with the products characteristics to predict delta and then determine what the new market share make up would be. So you won’t have delta initially for the new good and won’t we able to do the above calculation.

**Comment by jeffgortmaker** [comment]
Right, so given demand parameters, the Berry inversion solves for `delta_jt` as a function of market shares and product characteristics. In the logit case we have an analytic expression, but in the general case we have to solve a nonlinear system, e.g. with the fixed point algorithm suggested by BLP (1995). Section 3.2 in [this more recent paper](https://www.annualreviews.org/doi/abs/10.1146/annurev-economics-080315-015050) may be useful to you for more on this.

But this is just for estimation. You are right to point out that under a counterfactual with a new good `k` that wasn't there during estimation, it will generally be unclear what to use for `xi_kt`.

You may see researchers check whether their counterfactual results are robust to a number of assumptions on `xi_kt`, such as assuming `xi_kt = E[xi_kt] = 0`, assuming it is equal to that of some comparable product, or assuming that it is distributed according to the estimated distribution of `xi_jt` (or some distribution conditional on observed characteristics) and solve for the implied distribution of counterfactual outcomes under different realizations. Depending on your empirical setting, one, multiple, or none of these may be reasonable.
