### ISSUE TITLE
bounding initial values

### ISSUE THREAD

**Issue by austinbean** [jeffgortmaker/pyblp#98]
This might just be a syntax question!

I'd like to put some bounds on parameters to limit the search space.   

From the [docs](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Optimization.html#pyblp.Optimization) for pbylp.Optimization, it sounds like I should be able to pass `method_options={'gtol': 1e-4, 'bounds': [(l1, u1), ..., (lN,uN)]}`, since these options will be passed to `scipy.optimize` which [takes the optional argument](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) `bounds`.  

Instead I get the error: `TypeError: scipy_optimizer() got multiple values for argument 'bounds`

As a quick example :

`import pyblp`
`import numpy as np`
`import pandas as pd`
`product_data = pd.read_csv(pyblp.data.NEVO_PRODUCTS_LOCATION)`
`X1_formulation = pyblp.Formulation('0 + prices', absorb='C(product_ids)')`
`X2_formulation = pyblp.Formulation('1 + prices + sugar + mushy')`
`product_formulations = (X1_formulation, X2_formulation)`
`mc_integration = pyblp.Integration('monte_carlo', size=50, specification_options={'seed': 0})`
`mc_problem = pyblp.Problem(product_formulations, product_data, integration=mc_integration)`
`bfgs = pyblp.Optimization('bfgs', method_options={'gtol': 1e-4, 'bounds': [(-1.0, 1.0),(-1.0, 1.0),(-1.0, 1.0),(-1.0, 1.0)]})`
`results1 = mc_problem.solve(sigma=np.ones((4, 4)), optimization=bfgs)`

(The length of the vector `bounds` above does not matter in generating the error.)

Full stacktrace:

Traceback (most recent call last):
  File "bounds_ex.py", line 11, in <module>
    results1 = mc_problem.solve(sigma=np.ones((4, 4)), optimization=bfgs)
  File "/Users/austinbean/opt/anaconda3/lib/python3.7/site-packages/pyblp/economies/problem.py", line 638, in solve
    theta, optimization_stats = optimization._optimize(theta, theta_bounds, wrapper)
  File "/Users/austinbean/opt/anaconda3/lib/python3.7/site-packages/pyblp/configurations/optimization.py", line 290, in _optimize
    raw_initial, raw_bounds, objective_wrapper, iteration_callback, **self._method_options
TypeError: scipy_optimizer() got multiple values for argument 'bounds'

I am not normally a Python user, but some Googling suggested that perhaps there is an extra object named `bounds` running around which is confusing `scipy_optimizer` which takes that as a keyword argument?

**Comment by jeffgortmaker** [comment]
Right, you should use the PyBLP interface for bounds, not the `scipy.optimize` interface. PyBLP will figure out how to convert the `sigma_bounds`, `pi_bounds`, etc. you pass to [`Problem.solve`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Problem.solve.html) into bounds (for theta) and pass these to `scipy.optimize` itself. You're getting the error because PyBLP is already passing the `bounds` argument.

**Comment by austinbean** [comment]
Thanks!  Indeed it was a syntax question.

If anyone else finds this issue after running into a similar problem, following Jeff's suggestion one way of doing what I wanted to do in the example above would be like this:

`bfgs = pyblp.Optimization('bfgs', method_options={'gtol': 1e-4})`
`sigma_lower = (-2)*np.ones((4,4))`
`sigma_upper = 2*np.ones((4,4))`
`results1 = mc_problem.solve(sigma=np.ones((4, 4)), sigma_bounds=(sigma_lower, sigma_upper), optimization=bfgs)`

Where the constraint is that `sigma_upper` and `sigma_lower` must have the same shape as `sigma` and the initial values in `sigma` must lie within the bounds.

**Comment by jeffgortmaker** [comment]
Perfect!
