### ISSUE TITLE
Searching over variances (diagonal Sigma only)

### ISSUE THREAD

**Issue by fpinter** [jeffgortmaker/pyblp#99]
[Ketz 2019](https://doi.org/10.1016/j.jeconom.2019.02.008) documents that, when the Sigma matrix is diagonal, searching over variances has a superior numerical performance to searching over standard deviations. (In addition, the alternative inference methods of [Ketz 2018](http://www.parisschoolofeconomics.com/ketz-philipp/SubvectorInferenceBoundary.pdf) only work when you search over variances. In principle these methods are widely useful since sigmas are often close to zero.)

Jeff, I know we discussed this at some point, but I was reminded of it recently and wanted to put it here to see if you had more thoughts about it and to let others express interest.

**Comment by chrisconlon** [comment]
Would this require adjusting the Jacobian of $\xi$i w.r.t sigma by premultiplying by $1/(2 sigma_k)$?  (eqn 7) in the Ketz 2019 paper -- or would it require something more involved?

**Comment by jeffgortmaker** [comment]
I think we'd want to modify the underlying methods that compute [d u_ijt / d theta](https://github.com/jeffgortmaker/pyblp/blob/afdf4a9470437d6e733c4705d72f28c835289902/pyblp/markets/market.py#L646) and [d s_ijt / d theta](https://github.com/jeffgortmaker/pyblp/blob/afdf4a9470437d6e733c4705d72f28c835289902/pyblp/markets/market.py#L665), and this would probably imply that adjustment.

We'd also need an API, so something like an argument `sigma_type='variances'` in `Problem.solve`. Unless I missed something about how to handle correlated random coefficients, we'd want to raise an exception if you try to give a non-diagonal `sigma`. Although a more general API would allow for some random coefficients to be parameterized in terms of their variances, and others (which could be correlated) in terms of standard deviations.

But I'll keep this open for now as a reminder -- we've heard about this a couple of times, but I think not so much that it'd be high up on our to-do list.

**Comment by jeffgortmaker** [comment]
This isn't something that we've seen much more demand for, so I'm going to close it for now. Maybe we'll re-visit sometime in the future.
